
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Instance
 * 
 */
export type Instance = Prisma.InstanceModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model Permission
 * 
 */
export type Permission = Prisma.PermissionModel
/**
 * Model Organization
 * 
 */
export type Organization = Prisma.OrganizationModel
/**
 * Model UserOrganization
 * 
 */
export type UserOrganization = Prisma.UserOrganizationModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model UserProject
 * 
 */
export type UserProject = Prisma.UserProjectModel
/**
 * Model Branch
 * 
 */
export type Branch = Prisma.BranchModel
/**
 * Model Revision
 * 
 */
export type Revision = Prisma.RevisionModel
/**
 * Model EndpointVersion
 * 
 */
export type EndpointVersion = Prisma.EndpointVersionModel
/**
 * Model Endpoint
 * 
 */
export type Endpoint = Prisma.EndpointModel
/**
 * Model Table
 * 
 */
export type Table = Prisma.TableModel
/**
 * Model Row
 * 
 */
export type Row = Prisma.RowModel
