
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const RoleLevel = {
  System: 'System',
  Organization: 'Organization',
  Project: 'Project'
} as const

export type RoleLevel = (typeof RoleLevel)[keyof typeof RoleLevel]


export const EndpointType = {
  GRAPHQL: 'GRAPHQL',
  REST_API: 'REST_API'
} as const

export type EndpointType = (typeof EndpointType)[keyof typeof EndpointType]
