
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Instance: 'Instance',
  User: 'User',
  Role: 'Role',
  Permission: 'Permission',
  Organization: 'Organization',
  UserOrganization: 'UserOrganization',
  Project: 'Project',
  UserProject: 'UserProject',
  Branch: 'Branch',
  Revision: 'Revision',
  EndpointVersion: 'EndpointVersion',
  Endpoint: 'Endpoint',
  Table: 'Table',
  Row: 'Row'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const InstanceScalarFieldEnum = {
  id: 'id'
} as const

export type InstanceScalarFieldEnum = (typeof InstanceScalarFieldEnum)[keyof typeof InstanceScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  email: 'email',
  username: 'username',
  password: 'password',
  isEmailConfirmed: 'isEmailConfirmed',
  emailCode: 'emailCode',
  roleId: 'roleId'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const RoleScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  level: 'level',
  isCustom: 'isCustom'
} as const

export type RoleScalarFieldEnum = (typeof RoleScalarFieldEnum)[keyof typeof RoleScalarFieldEnum]


export const PermissionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  action: 'action',
  subject: 'subject',
  condition: 'condition'
} as const

export type PermissionScalarFieldEnum = (typeof PermissionScalarFieldEnum)[keyof typeof PermissionScalarFieldEnum]


export const OrganizationScalarFieldEnum = {
  id: 'id',
  createdId: 'createdId'
} as const

export type OrganizationScalarFieldEnum = (typeof OrganizationScalarFieldEnum)[keyof typeof OrganizationScalarFieldEnum]


export const UserOrganizationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  organizationId: 'organizationId',
  userId: 'userId',
  roleId: 'roleId'
} as const

export type UserOrganizationScalarFieldEnum = (typeof UserOrganizationScalarFieldEnum)[keyof typeof UserOrganizationScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  isPublic: 'isPublic',
  organizationId: 'organizationId'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const UserProjectScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  projectId: 'projectId',
  userId: 'userId',
  roleId: 'roleId'
} as const

export type UserProjectScalarFieldEnum = (typeof UserProjectScalarFieldEnum)[keyof typeof UserProjectScalarFieldEnum]


export const BranchScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  isRoot: 'isRoot',
  name: 'name',
  projectId: 'projectId'
} as const

export type BranchScalarFieldEnum = (typeof BranchScalarFieldEnum)[keyof typeof BranchScalarFieldEnum]


export const RevisionScalarFieldEnum = {
  id: 'id',
  sequence: 'sequence',
  createdAt: 'createdAt',
  comment: 'comment',
  isHead: 'isHead',
  isDraft: 'isDraft',
  isStart: 'isStart',
  hasChanges: 'hasChanges',
  branchId: 'branchId',
  parentId: 'parentId'
} as const

export type RevisionScalarFieldEnum = (typeof RevisionScalarFieldEnum)[keyof typeof RevisionScalarFieldEnum]


export const EndpointVersionScalarFieldEnum = {
  id: 'id',
  type: 'type',
  version: 'version'
} as const

export type EndpointVersionScalarFieldEnum = (typeof EndpointVersionScalarFieldEnum)[keyof typeof EndpointVersionScalarFieldEnum]


export const EndpointScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  type: 'type',
  revisionId: 'revisionId',
  isDeleted: 'isDeleted',
  versionId: 'versionId'
} as const

export type EndpointScalarFieldEnum = (typeof EndpointScalarFieldEnum)[keyof typeof EndpointScalarFieldEnum]


export const TableScalarFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  readonly: 'readonly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  system: 'system'
} as const

export type TableScalarFieldEnum = (typeof TableScalarFieldEnum)[keyof typeof TableScalarFieldEnum]


export const RowScalarFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  readonly: 'readonly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  data: 'data',
  meta: 'meta',
  hash: 'hash',
  schemaHash: 'schemaHash'
} as const

export type RowScalarFieldEnum = (typeof RowScalarFieldEnum)[keyof typeof RowScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const InstanceOrderByRelevanceFieldEnum = {
  id: 'id'
} as const

export type InstanceOrderByRelevanceFieldEnum = (typeof InstanceOrderByRelevanceFieldEnum)[keyof typeof InstanceOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  email: 'email',
  username: 'username',
  password: 'password',
  emailCode: 'emailCode',
  roleId: 'roleId'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const RoleOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type RoleOrderByRelevanceFieldEnum = (typeof RoleOrderByRelevanceFieldEnum)[keyof typeof RoleOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const PermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  action: 'action',
  subject: 'subject'
} as const

export type PermissionOrderByRelevanceFieldEnum = (typeof PermissionOrderByRelevanceFieldEnum)[keyof typeof PermissionOrderByRelevanceFieldEnum]


export const OrganizationOrderByRelevanceFieldEnum = {
  id: 'id',
  createdId: 'createdId'
} as const

export type OrganizationOrderByRelevanceFieldEnum = (typeof OrganizationOrderByRelevanceFieldEnum)[keyof typeof OrganizationOrderByRelevanceFieldEnum]


export const UserOrganizationOrderByRelevanceFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  roleId: 'roleId'
} as const

export type UserOrganizationOrderByRelevanceFieldEnum = (typeof UserOrganizationOrderByRelevanceFieldEnum)[keyof typeof UserOrganizationOrderByRelevanceFieldEnum]


export const ProjectOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  organizationId: 'organizationId'
} as const

export type ProjectOrderByRelevanceFieldEnum = (typeof ProjectOrderByRelevanceFieldEnum)[keyof typeof ProjectOrderByRelevanceFieldEnum]


export const UserProjectOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  userId: 'userId',
  roleId: 'roleId'
} as const

export type UserProjectOrderByRelevanceFieldEnum = (typeof UserProjectOrderByRelevanceFieldEnum)[keyof typeof UserProjectOrderByRelevanceFieldEnum]


export const BranchOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  projectId: 'projectId'
} as const

export type BranchOrderByRelevanceFieldEnum = (typeof BranchOrderByRelevanceFieldEnum)[keyof typeof BranchOrderByRelevanceFieldEnum]


export const RevisionOrderByRelevanceFieldEnum = {
  id: 'id',
  comment: 'comment',
  branchId: 'branchId',
  parentId: 'parentId'
} as const

export type RevisionOrderByRelevanceFieldEnum = (typeof RevisionOrderByRelevanceFieldEnum)[keyof typeof RevisionOrderByRelevanceFieldEnum]


export const EndpointVersionOrderByRelevanceFieldEnum = {
  id: 'id'
} as const

export type EndpointVersionOrderByRelevanceFieldEnum = (typeof EndpointVersionOrderByRelevanceFieldEnum)[keyof typeof EndpointVersionOrderByRelevanceFieldEnum]


export const EndpointOrderByRelevanceFieldEnum = {
  id: 'id',
  revisionId: 'revisionId',
  versionId: 'versionId'
} as const

export type EndpointOrderByRelevanceFieldEnum = (typeof EndpointOrderByRelevanceFieldEnum)[keyof typeof EndpointOrderByRelevanceFieldEnum]


export const TableOrderByRelevanceFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id'
} as const

export type TableOrderByRelevanceFieldEnum = (typeof TableOrderByRelevanceFieldEnum)[keyof typeof TableOrderByRelevanceFieldEnum]


export const RowOrderByRelevanceFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  hash: 'hash',
  schemaHash: 'schemaHash'
} as const

export type RowOrderByRelevanceFieldEnum = (typeof RowOrderByRelevanceFieldEnum)[keyof typeof RowOrderByRelevanceFieldEnum]

