
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Endpoint` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Endpoint
 * 
 */
export type EndpointModel = runtime.Types.Result.DefaultSelection<Prisma.$EndpointPayload>

export type AggregateEndpoint = {
  _count: EndpointCountAggregateOutputType | null
  _min: EndpointMinAggregateOutputType | null
  _max: EndpointMaxAggregateOutputType | null
}

export type EndpointMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  type: $Enums.EndpointType | null
  revisionId: string | null
  isDeleted: boolean | null
  versionId: string | null
}

export type EndpointMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  type: $Enums.EndpointType | null
  revisionId: string | null
  isDeleted: boolean | null
  versionId: string | null
}

export type EndpointCountAggregateOutputType = {
  id: number
  createdAt: number
  type: number
  revisionId: number
  isDeleted: number
  versionId: number
  _all: number
}


export type EndpointMinAggregateInputType = {
  id?: true
  createdAt?: true
  type?: true
  revisionId?: true
  isDeleted?: true
  versionId?: true
}

export type EndpointMaxAggregateInputType = {
  id?: true
  createdAt?: true
  type?: true
  revisionId?: true
  isDeleted?: true
  versionId?: true
}

export type EndpointCountAggregateInputType = {
  id?: true
  createdAt?: true
  type?: true
  revisionId?: true
  isDeleted?: true
  versionId?: true
  _all?: true
}

export type EndpointAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Endpoint to aggregate.
   */
  where?: Prisma.EndpointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Endpoints to fetch.
   */
  orderBy?: Prisma.EndpointOrderByWithRelationInput | Prisma.EndpointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EndpointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Endpoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Endpoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Endpoints
  **/
  _count?: true | EndpointCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EndpointMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EndpointMaxAggregateInputType
}

export type GetEndpointAggregateType<T extends EndpointAggregateArgs> = {
      [P in keyof T & keyof AggregateEndpoint]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEndpoint[P]>
    : Prisma.GetScalarType<T[P], AggregateEndpoint[P]>
}




export type EndpointGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EndpointWhereInput
  orderBy?: Prisma.EndpointOrderByWithAggregationInput | Prisma.EndpointOrderByWithAggregationInput[]
  by: Prisma.EndpointScalarFieldEnum[] | Prisma.EndpointScalarFieldEnum
  having?: Prisma.EndpointScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EndpointCountAggregateInputType | true
  _min?: EndpointMinAggregateInputType
  _max?: EndpointMaxAggregateInputType
}

export type EndpointGroupByOutputType = {
  id: string
  createdAt: Date
  type: $Enums.EndpointType
  revisionId: string
  isDeleted: boolean
  versionId: string
  _count: EndpointCountAggregateOutputType | null
  _min: EndpointMinAggregateOutputType | null
  _max: EndpointMaxAggregateOutputType | null
}

type GetEndpointGroupByPayload<T extends EndpointGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EndpointGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EndpointGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EndpointGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EndpointGroupByOutputType[P]>
      }
    >
  >



export type EndpointWhereInput = {
  AND?: Prisma.EndpointWhereInput | Prisma.EndpointWhereInput[]
  OR?: Prisma.EndpointWhereInput[]
  NOT?: Prisma.EndpointWhereInput | Prisma.EndpointWhereInput[]
  id?: Prisma.StringFilter<"Endpoint"> | string
  createdAt?: Prisma.DateTimeFilter<"Endpoint"> | Date | string
  type?: Prisma.EnumEndpointTypeFilter<"Endpoint"> | $Enums.EndpointType
  revisionId?: Prisma.StringFilter<"Endpoint"> | string
  isDeleted?: Prisma.BoolFilter<"Endpoint"> | boolean
  versionId?: Prisma.StringFilter<"Endpoint"> | string
  version?: Prisma.XOR<Prisma.EndpointVersionScalarRelationFilter, Prisma.EndpointVersionWhereInput>
  revision?: Prisma.XOR<Prisma.RevisionScalarRelationFilter, Prisma.RevisionWhereInput>
}

export type EndpointOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  type?: Prisma.SortOrder
  revisionId?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  versionId?: Prisma.SortOrder
  version?: Prisma.EndpointVersionOrderByWithRelationInput
  revision?: Prisma.RevisionOrderByWithRelationInput
  _relevance?: Prisma.EndpointOrderByRelevanceInput
}

export type EndpointWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  revisionId_type?: Prisma.EndpointRevisionIdTypeCompoundUniqueInput
  AND?: Prisma.EndpointWhereInput | Prisma.EndpointWhereInput[]
  OR?: Prisma.EndpointWhereInput[]
  NOT?: Prisma.EndpointWhereInput | Prisma.EndpointWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Endpoint"> | Date | string
  type?: Prisma.EnumEndpointTypeFilter<"Endpoint"> | $Enums.EndpointType
  revisionId?: Prisma.StringFilter<"Endpoint"> | string
  isDeleted?: Prisma.BoolFilter<"Endpoint"> | boolean
  versionId?: Prisma.StringFilter<"Endpoint"> | string
  version?: Prisma.XOR<Prisma.EndpointVersionScalarRelationFilter, Prisma.EndpointVersionWhereInput>
  revision?: Prisma.XOR<Prisma.RevisionScalarRelationFilter, Prisma.RevisionWhereInput>
}, "id" | "revisionId_type">

export type EndpointOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  type?: Prisma.SortOrder
  revisionId?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  versionId?: Prisma.SortOrder
  _count?: Prisma.EndpointCountOrderByAggregateInput
  _max?: Prisma.EndpointMaxOrderByAggregateInput
  _min?: Prisma.EndpointMinOrderByAggregateInput
}

export type EndpointScalarWhereWithAggregatesInput = {
  AND?: Prisma.EndpointScalarWhereWithAggregatesInput | Prisma.EndpointScalarWhereWithAggregatesInput[]
  OR?: Prisma.EndpointScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EndpointScalarWhereWithAggregatesInput | Prisma.EndpointScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Endpoint"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Endpoint"> | Date | string
  type?: Prisma.EnumEndpointTypeWithAggregatesFilter<"Endpoint"> | $Enums.EndpointType
  revisionId?: Prisma.StringWithAggregatesFilter<"Endpoint"> | string
  isDeleted?: Prisma.BoolWithAggregatesFilter<"Endpoint"> | boolean
  versionId?: Prisma.StringWithAggregatesFilter<"Endpoint"> | string
}

export type EndpointCreateInput = {
  id: string
  createdAt?: Date | string
  type: $Enums.EndpointType
  isDeleted?: boolean
  version: Prisma.EndpointVersionCreateNestedOneWithoutEndpointInput
  revision: Prisma.RevisionCreateNestedOneWithoutEndpointsInput
}

export type EndpointUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  type: $Enums.EndpointType
  revisionId: string
  isDeleted?: boolean
  versionId: string
}

export type EndpointUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  version?: Prisma.EndpointVersionUpdateOneRequiredWithoutEndpointNestedInput
  revision?: Prisma.RevisionUpdateOneRequiredWithoutEndpointsNestedInput
}

export type EndpointUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  revisionId?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EndpointCreateManyInput = {
  id: string
  createdAt?: Date | string
  type: $Enums.EndpointType
  revisionId: string
  isDeleted?: boolean
  versionId: string
}

export type EndpointUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type EndpointUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  revisionId?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EndpointListRelationFilter = {
  every?: Prisma.EndpointWhereInput
  some?: Prisma.EndpointWhereInput
  none?: Prisma.EndpointWhereInput
}

export type EndpointOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EndpointOrderByRelevanceInput = {
  fields: Prisma.EndpointOrderByRelevanceFieldEnum | Prisma.EndpointOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type EndpointRevisionIdTypeCompoundUniqueInput = {
  revisionId: string
  type: $Enums.EndpointType
}

export type EndpointCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  type?: Prisma.SortOrder
  revisionId?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  versionId?: Prisma.SortOrder
}

export type EndpointMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  type?: Prisma.SortOrder
  revisionId?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  versionId?: Prisma.SortOrder
}

export type EndpointMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  type?: Prisma.SortOrder
  revisionId?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  versionId?: Prisma.SortOrder
}

export type EndpointCreateNestedManyWithoutRevisionInput = {
  create?: Prisma.XOR<Prisma.EndpointCreateWithoutRevisionInput, Prisma.EndpointUncheckedCreateWithoutRevisionInput> | Prisma.EndpointCreateWithoutRevisionInput[] | Prisma.EndpointUncheckedCreateWithoutRevisionInput[]
  connectOrCreate?: Prisma.EndpointCreateOrConnectWithoutRevisionInput | Prisma.EndpointCreateOrConnectWithoutRevisionInput[]
  createMany?: Prisma.EndpointCreateManyRevisionInputEnvelope
  connect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
}

export type EndpointUncheckedCreateNestedManyWithoutRevisionInput = {
  create?: Prisma.XOR<Prisma.EndpointCreateWithoutRevisionInput, Prisma.EndpointUncheckedCreateWithoutRevisionInput> | Prisma.EndpointCreateWithoutRevisionInput[] | Prisma.EndpointUncheckedCreateWithoutRevisionInput[]
  connectOrCreate?: Prisma.EndpointCreateOrConnectWithoutRevisionInput | Prisma.EndpointCreateOrConnectWithoutRevisionInput[]
  createMany?: Prisma.EndpointCreateManyRevisionInputEnvelope
  connect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
}

export type EndpointUpdateManyWithoutRevisionNestedInput = {
  create?: Prisma.XOR<Prisma.EndpointCreateWithoutRevisionInput, Prisma.EndpointUncheckedCreateWithoutRevisionInput> | Prisma.EndpointCreateWithoutRevisionInput[] | Prisma.EndpointUncheckedCreateWithoutRevisionInput[]
  connectOrCreate?: Prisma.EndpointCreateOrConnectWithoutRevisionInput | Prisma.EndpointCreateOrConnectWithoutRevisionInput[]
  upsert?: Prisma.EndpointUpsertWithWhereUniqueWithoutRevisionInput | Prisma.EndpointUpsertWithWhereUniqueWithoutRevisionInput[]
  createMany?: Prisma.EndpointCreateManyRevisionInputEnvelope
  set?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  disconnect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  delete?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  connect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  update?: Prisma.EndpointUpdateWithWhereUniqueWithoutRevisionInput | Prisma.EndpointUpdateWithWhereUniqueWithoutRevisionInput[]
  updateMany?: Prisma.EndpointUpdateManyWithWhereWithoutRevisionInput | Prisma.EndpointUpdateManyWithWhereWithoutRevisionInput[]
  deleteMany?: Prisma.EndpointScalarWhereInput | Prisma.EndpointScalarWhereInput[]
}

export type EndpointUncheckedUpdateManyWithoutRevisionNestedInput = {
  create?: Prisma.XOR<Prisma.EndpointCreateWithoutRevisionInput, Prisma.EndpointUncheckedCreateWithoutRevisionInput> | Prisma.EndpointCreateWithoutRevisionInput[] | Prisma.EndpointUncheckedCreateWithoutRevisionInput[]
  connectOrCreate?: Prisma.EndpointCreateOrConnectWithoutRevisionInput | Prisma.EndpointCreateOrConnectWithoutRevisionInput[]
  upsert?: Prisma.EndpointUpsertWithWhereUniqueWithoutRevisionInput | Prisma.EndpointUpsertWithWhereUniqueWithoutRevisionInput[]
  createMany?: Prisma.EndpointCreateManyRevisionInputEnvelope
  set?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  disconnect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  delete?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  connect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  update?: Prisma.EndpointUpdateWithWhereUniqueWithoutRevisionInput | Prisma.EndpointUpdateWithWhereUniqueWithoutRevisionInput[]
  updateMany?: Prisma.EndpointUpdateManyWithWhereWithoutRevisionInput | Prisma.EndpointUpdateManyWithWhereWithoutRevisionInput[]
  deleteMany?: Prisma.EndpointScalarWhereInput | Prisma.EndpointScalarWhereInput[]
}

export type EndpointCreateNestedManyWithoutVersionInput = {
  create?: Prisma.XOR<Prisma.EndpointCreateWithoutVersionInput, Prisma.EndpointUncheckedCreateWithoutVersionInput> | Prisma.EndpointCreateWithoutVersionInput[] | Prisma.EndpointUncheckedCreateWithoutVersionInput[]
  connectOrCreate?: Prisma.EndpointCreateOrConnectWithoutVersionInput | Prisma.EndpointCreateOrConnectWithoutVersionInput[]
  createMany?: Prisma.EndpointCreateManyVersionInputEnvelope
  connect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
}

export type EndpointUncheckedCreateNestedManyWithoutVersionInput = {
  create?: Prisma.XOR<Prisma.EndpointCreateWithoutVersionInput, Prisma.EndpointUncheckedCreateWithoutVersionInput> | Prisma.EndpointCreateWithoutVersionInput[] | Prisma.EndpointUncheckedCreateWithoutVersionInput[]
  connectOrCreate?: Prisma.EndpointCreateOrConnectWithoutVersionInput | Prisma.EndpointCreateOrConnectWithoutVersionInput[]
  createMany?: Prisma.EndpointCreateManyVersionInputEnvelope
  connect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
}

export type EndpointUpdateManyWithoutVersionNestedInput = {
  create?: Prisma.XOR<Prisma.EndpointCreateWithoutVersionInput, Prisma.EndpointUncheckedCreateWithoutVersionInput> | Prisma.EndpointCreateWithoutVersionInput[] | Prisma.EndpointUncheckedCreateWithoutVersionInput[]
  connectOrCreate?: Prisma.EndpointCreateOrConnectWithoutVersionInput | Prisma.EndpointCreateOrConnectWithoutVersionInput[]
  upsert?: Prisma.EndpointUpsertWithWhereUniqueWithoutVersionInput | Prisma.EndpointUpsertWithWhereUniqueWithoutVersionInput[]
  createMany?: Prisma.EndpointCreateManyVersionInputEnvelope
  set?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  disconnect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  delete?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  connect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  update?: Prisma.EndpointUpdateWithWhereUniqueWithoutVersionInput | Prisma.EndpointUpdateWithWhereUniqueWithoutVersionInput[]
  updateMany?: Prisma.EndpointUpdateManyWithWhereWithoutVersionInput | Prisma.EndpointUpdateManyWithWhereWithoutVersionInput[]
  deleteMany?: Prisma.EndpointScalarWhereInput | Prisma.EndpointScalarWhereInput[]
}

export type EndpointUncheckedUpdateManyWithoutVersionNestedInput = {
  create?: Prisma.XOR<Prisma.EndpointCreateWithoutVersionInput, Prisma.EndpointUncheckedCreateWithoutVersionInput> | Prisma.EndpointCreateWithoutVersionInput[] | Prisma.EndpointUncheckedCreateWithoutVersionInput[]
  connectOrCreate?: Prisma.EndpointCreateOrConnectWithoutVersionInput | Prisma.EndpointCreateOrConnectWithoutVersionInput[]
  upsert?: Prisma.EndpointUpsertWithWhereUniqueWithoutVersionInput | Prisma.EndpointUpsertWithWhereUniqueWithoutVersionInput[]
  createMany?: Prisma.EndpointCreateManyVersionInputEnvelope
  set?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  disconnect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  delete?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  connect?: Prisma.EndpointWhereUniqueInput | Prisma.EndpointWhereUniqueInput[]
  update?: Prisma.EndpointUpdateWithWhereUniqueWithoutVersionInput | Prisma.EndpointUpdateWithWhereUniqueWithoutVersionInput[]
  updateMany?: Prisma.EndpointUpdateManyWithWhereWithoutVersionInput | Prisma.EndpointUpdateManyWithWhereWithoutVersionInput[]
  deleteMany?: Prisma.EndpointScalarWhereInput | Prisma.EndpointScalarWhereInput[]
}

export type EndpointCreateWithoutRevisionInput = {
  id: string
  createdAt?: Date | string
  type: $Enums.EndpointType
  isDeleted?: boolean
  version: Prisma.EndpointVersionCreateNestedOneWithoutEndpointInput
}

export type EndpointUncheckedCreateWithoutRevisionInput = {
  id: string
  createdAt?: Date | string
  type: $Enums.EndpointType
  isDeleted?: boolean
  versionId: string
}

export type EndpointCreateOrConnectWithoutRevisionInput = {
  where: Prisma.EndpointWhereUniqueInput
  create: Prisma.XOR<Prisma.EndpointCreateWithoutRevisionInput, Prisma.EndpointUncheckedCreateWithoutRevisionInput>
}

export type EndpointCreateManyRevisionInputEnvelope = {
  data: Prisma.EndpointCreateManyRevisionInput | Prisma.EndpointCreateManyRevisionInput[]
  skipDuplicates?: boolean
}

export type EndpointUpsertWithWhereUniqueWithoutRevisionInput = {
  where: Prisma.EndpointWhereUniqueInput
  update: Prisma.XOR<Prisma.EndpointUpdateWithoutRevisionInput, Prisma.EndpointUncheckedUpdateWithoutRevisionInput>
  create: Prisma.XOR<Prisma.EndpointCreateWithoutRevisionInput, Prisma.EndpointUncheckedCreateWithoutRevisionInput>
}

export type EndpointUpdateWithWhereUniqueWithoutRevisionInput = {
  where: Prisma.EndpointWhereUniqueInput
  data: Prisma.XOR<Prisma.EndpointUpdateWithoutRevisionInput, Prisma.EndpointUncheckedUpdateWithoutRevisionInput>
}

export type EndpointUpdateManyWithWhereWithoutRevisionInput = {
  where: Prisma.EndpointScalarWhereInput
  data: Prisma.XOR<Prisma.EndpointUpdateManyMutationInput, Prisma.EndpointUncheckedUpdateManyWithoutRevisionInput>
}

export type EndpointScalarWhereInput = {
  AND?: Prisma.EndpointScalarWhereInput | Prisma.EndpointScalarWhereInput[]
  OR?: Prisma.EndpointScalarWhereInput[]
  NOT?: Prisma.EndpointScalarWhereInput | Prisma.EndpointScalarWhereInput[]
  id?: Prisma.StringFilter<"Endpoint"> | string
  createdAt?: Prisma.DateTimeFilter<"Endpoint"> | Date | string
  type?: Prisma.EnumEndpointTypeFilter<"Endpoint"> | $Enums.EndpointType
  revisionId?: Prisma.StringFilter<"Endpoint"> | string
  isDeleted?: Prisma.BoolFilter<"Endpoint"> | boolean
  versionId?: Prisma.StringFilter<"Endpoint"> | string
}

export type EndpointCreateWithoutVersionInput = {
  id: string
  createdAt?: Date | string
  type: $Enums.EndpointType
  isDeleted?: boolean
  revision: Prisma.RevisionCreateNestedOneWithoutEndpointsInput
}

export type EndpointUncheckedCreateWithoutVersionInput = {
  id: string
  createdAt?: Date | string
  type: $Enums.EndpointType
  revisionId: string
  isDeleted?: boolean
}

export type EndpointCreateOrConnectWithoutVersionInput = {
  where: Prisma.EndpointWhereUniqueInput
  create: Prisma.XOR<Prisma.EndpointCreateWithoutVersionInput, Prisma.EndpointUncheckedCreateWithoutVersionInput>
}

export type EndpointCreateManyVersionInputEnvelope = {
  data: Prisma.EndpointCreateManyVersionInput | Prisma.EndpointCreateManyVersionInput[]
  skipDuplicates?: boolean
}

export type EndpointUpsertWithWhereUniqueWithoutVersionInput = {
  where: Prisma.EndpointWhereUniqueInput
  update: Prisma.XOR<Prisma.EndpointUpdateWithoutVersionInput, Prisma.EndpointUncheckedUpdateWithoutVersionInput>
  create: Prisma.XOR<Prisma.EndpointCreateWithoutVersionInput, Prisma.EndpointUncheckedCreateWithoutVersionInput>
}

export type EndpointUpdateWithWhereUniqueWithoutVersionInput = {
  where: Prisma.EndpointWhereUniqueInput
  data: Prisma.XOR<Prisma.EndpointUpdateWithoutVersionInput, Prisma.EndpointUncheckedUpdateWithoutVersionInput>
}

export type EndpointUpdateManyWithWhereWithoutVersionInput = {
  where: Prisma.EndpointScalarWhereInput
  data: Prisma.XOR<Prisma.EndpointUpdateManyMutationInput, Prisma.EndpointUncheckedUpdateManyWithoutVersionInput>
}

export type EndpointCreateManyRevisionInput = {
  id: string
  createdAt?: Date | string
  type: $Enums.EndpointType
  isDeleted?: boolean
  versionId: string
}

export type EndpointUpdateWithoutRevisionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  version?: Prisma.EndpointVersionUpdateOneRequiredWithoutEndpointNestedInput
}

export type EndpointUncheckedUpdateWithoutRevisionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EndpointUncheckedUpdateManyWithoutRevisionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EndpointCreateManyVersionInput = {
  id: string
  createdAt?: Date | string
  type: $Enums.EndpointType
  revisionId: string
  isDeleted?: boolean
}

export type EndpointUpdateWithoutVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  revision?: Prisma.RevisionUpdateOneRequiredWithoutEndpointsNestedInput
}

export type EndpointUncheckedUpdateWithoutVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  revisionId?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type EndpointUncheckedUpdateManyWithoutVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  revisionId?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type EndpointSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  type?: boolean
  revisionId?: boolean
  isDeleted?: boolean
  versionId?: boolean
  version?: boolean | Prisma.EndpointVersionDefaultArgs<ExtArgs>
  revision?: boolean | Prisma.RevisionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["endpoint"]>

export type EndpointSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  type?: boolean
  revisionId?: boolean
  isDeleted?: boolean
  versionId?: boolean
  version?: boolean | Prisma.EndpointVersionDefaultArgs<ExtArgs>
  revision?: boolean | Prisma.RevisionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["endpoint"]>

export type EndpointSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  type?: boolean
  revisionId?: boolean
  isDeleted?: boolean
  versionId?: boolean
  version?: boolean | Prisma.EndpointVersionDefaultArgs<ExtArgs>
  revision?: boolean | Prisma.RevisionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["endpoint"]>

export type EndpointSelectScalar = {
  id?: boolean
  createdAt?: boolean
  type?: boolean
  revisionId?: boolean
  isDeleted?: boolean
  versionId?: boolean
}

export type EndpointOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "type" | "revisionId" | "isDeleted" | "versionId", ExtArgs["result"]["endpoint"]>
export type EndpointInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  version?: boolean | Prisma.EndpointVersionDefaultArgs<ExtArgs>
  revision?: boolean | Prisma.RevisionDefaultArgs<ExtArgs>
}
export type EndpointIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  version?: boolean | Prisma.EndpointVersionDefaultArgs<ExtArgs>
  revision?: boolean | Prisma.RevisionDefaultArgs<ExtArgs>
}
export type EndpointIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  version?: boolean | Prisma.EndpointVersionDefaultArgs<ExtArgs>
  revision?: boolean | Prisma.RevisionDefaultArgs<ExtArgs>
}

export type $EndpointPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Endpoint"
  objects: {
    version: Prisma.$EndpointVersionPayload<ExtArgs>
    revision: Prisma.$RevisionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    type: $Enums.EndpointType
    revisionId: string
    isDeleted: boolean
    versionId: string
  }, ExtArgs["result"]["endpoint"]>
  composites: {}
}

export type EndpointGetPayload<S extends boolean | null | undefined | EndpointDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EndpointPayload, S>

export type EndpointCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EndpointFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EndpointCountAggregateInputType | true
  }

export interface EndpointDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Endpoint'], meta: { name: 'Endpoint' } }
  /**
   * Find zero or one Endpoint that matches the filter.
   * @param {EndpointFindUniqueArgs} args - Arguments to find a Endpoint
   * @example
   * // Get one Endpoint
   * const endpoint = await prisma.endpoint.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EndpointFindUniqueArgs>(args: Prisma.SelectSubset<T, EndpointFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EndpointClient<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Endpoint that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EndpointFindUniqueOrThrowArgs} args - Arguments to find a Endpoint
   * @example
   * // Get one Endpoint
   * const endpoint = await prisma.endpoint.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EndpointFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EndpointFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EndpointClient<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Endpoint that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointFindFirstArgs} args - Arguments to find a Endpoint
   * @example
   * // Get one Endpoint
   * const endpoint = await prisma.endpoint.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EndpointFindFirstArgs>(args?: Prisma.SelectSubset<T, EndpointFindFirstArgs<ExtArgs>>): Prisma.Prisma__EndpointClient<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Endpoint that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointFindFirstOrThrowArgs} args - Arguments to find a Endpoint
   * @example
   * // Get one Endpoint
   * const endpoint = await prisma.endpoint.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EndpointFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EndpointFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EndpointClient<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Endpoints that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Endpoints
   * const endpoints = await prisma.endpoint.findMany()
   * 
   * // Get first 10 Endpoints
   * const endpoints = await prisma.endpoint.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const endpointWithIdOnly = await prisma.endpoint.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EndpointFindManyArgs>(args?: Prisma.SelectSubset<T, EndpointFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Endpoint.
   * @param {EndpointCreateArgs} args - Arguments to create a Endpoint.
   * @example
   * // Create one Endpoint
   * const Endpoint = await prisma.endpoint.create({
   *   data: {
   *     // ... data to create a Endpoint
   *   }
   * })
   * 
   */
  create<T extends EndpointCreateArgs>(args: Prisma.SelectSubset<T, EndpointCreateArgs<ExtArgs>>): Prisma.Prisma__EndpointClient<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Endpoints.
   * @param {EndpointCreateManyArgs} args - Arguments to create many Endpoints.
   * @example
   * // Create many Endpoints
   * const endpoint = await prisma.endpoint.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EndpointCreateManyArgs>(args?: Prisma.SelectSubset<T, EndpointCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Endpoints and returns the data saved in the database.
   * @param {EndpointCreateManyAndReturnArgs} args - Arguments to create many Endpoints.
   * @example
   * // Create many Endpoints
   * const endpoint = await prisma.endpoint.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Endpoints and only return the `id`
   * const endpointWithIdOnly = await prisma.endpoint.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EndpointCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EndpointCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Endpoint.
   * @param {EndpointDeleteArgs} args - Arguments to delete one Endpoint.
   * @example
   * // Delete one Endpoint
   * const Endpoint = await prisma.endpoint.delete({
   *   where: {
   *     // ... filter to delete one Endpoint
   *   }
   * })
   * 
   */
  delete<T extends EndpointDeleteArgs>(args: Prisma.SelectSubset<T, EndpointDeleteArgs<ExtArgs>>): Prisma.Prisma__EndpointClient<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Endpoint.
   * @param {EndpointUpdateArgs} args - Arguments to update one Endpoint.
   * @example
   * // Update one Endpoint
   * const endpoint = await prisma.endpoint.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EndpointUpdateArgs>(args: Prisma.SelectSubset<T, EndpointUpdateArgs<ExtArgs>>): Prisma.Prisma__EndpointClient<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Endpoints.
   * @param {EndpointDeleteManyArgs} args - Arguments to filter Endpoints to delete.
   * @example
   * // Delete a few Endpoints
   * const { count } = await prisma.endpoint.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EndpointDeleteManyArgs>(args?: Prisma.SelectSubset<T, EndpointDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Endpoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Endpoints
   * const endpoint = await prisma.endpoint.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EndpointUpdateManyArgs>(args: Prisma.SelectSubset<T, EndpointUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Endpoints and returns the data updated in the database.
   * @param {EndpointUpdateManyAndReturnArgs} args - Arguments to update many Endpoints.
   * @example
   * // Update many Endpoints
   * const endpoint = await prisma.endpoint.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Endpoints and only return the `id`
   * const endpointWithIdOnly = await prisma.endpoint.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EndpointUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EndpointUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Endpoint.
   * @param {EndpointUpsertArgs} args - Arguments to update or create a Endpoint.
   * @example
   * // Update or create a Endpoint
   * const endpoint = await prisma.endpoint.upsert({
   *   create: {
   *     // ... data to create a Endpoint
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Endpoint we want to update
   *   }
   * })
   */
  upsert<T extends EndpointUpsertArgs>(args: Prisma.SelectSubset<T, EndpointUpsertArgs<ExtArgs>>): Prisma.Prisma__EndpointClient<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Endpoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointCountArgs} args - Arguments to filter Endpoints to count.
   * @example
   * // Count the number of Endpoints
   * const count = await prisma.endpoint.count({
   *   where: {
   *     // ... the filter for the Endpoints we want to count
   *   }
   * })
  **/
  count<T extends EndpointCountArgs>(
    args?: Prisma.Subset<T, EndpointCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EndpointCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Endpoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EndpointAggregateArgs>(args: Prisma.Subset<T, EndpointAggregateArgs>): Prisma.PrismaPromise<GetEndpointAggregateType<T>>

  /**
   * Group by Endpoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EndpointGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EndpointGroupByArgs['orderBy'] }
      : { orderBy?: EndpointGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EndpointGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEndpointGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Endpoint model
 */
readonly fields: EndpointFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Endpoint.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EndpointClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  version<T extends Prisma.EndpointVersionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EndpointVersionDefaultArgs<ExtArgs>>): Prisma.Prisma__EndpointVersionClient<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  revision<T extends Prisma.RevisionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RevisionDefaultArgs<ExtArgs>>): Prisma.Prisma__RevisionClient<runtime.Types.Result.GetResult<Prisma.$RevisionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Endpoint model
 */
export interface EndpointFieldRefs {
  readonly id: Prisma.FieldRef<"Endpoint", 'String'>
  readonly createdAt: Prisma.FieldRef<"Endpoint", 'DateTime'>
  readonly type: Prisma.FieldRef<"Endpoint", 'EndpointType'>
  readonly revisionId: Prisma.FieldRef<"Endpoint", 'String'>
  readonly isDeleted: Prisma.FieldRef<"Endpoint", 'Boolean'>
  readonly versionId: Prisma.FieldRef<"Endpoint", 'String'>
}
    

// Custom InputTypes
/**
 * Endpoint findUnique
 */
export type EndpointFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  /**
   * Filter, which Endpoint to fetch.
   */
  where: Prisma.EndpointWhereUniqueInput
}

/**
 * Endpoint findUniqueOrThrow
 */
export type EndpointFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  /**
   * Filter, which Endpoint to fetch.
   */
  where: Prisma.EndpointWhereUniqueInput
}

/**
 * Endpoint findFirst
 */
export type EndpointFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  /**
   * Filter, which Endpoint to fetch.
   */
  where?: Prisma.EndpointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Endpoints to fetch.
   */
  orderBy?: Prisma.EndpointOrderByWithRelationInput | Prisma.EndpointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Endpoints.
   */
  cursor?: Prisma.EndpointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Endpoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Endpoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Endpoints.
   */
  distinct?: Prisma.EndpointScalarFieldEnum | Prisma.EndpointScalarFieldEnum[]
}

/**
 * Endpoint findFirstOrThrow
 */
export type EndpointFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  /**
   * Filter, which Endpoint to fetch.
   */
  where?: Prisma.EndpointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Endpoints to fetch.
   */
  orderBy?: Prisma.EndpointOrderByWithRelationInput | Prisma.EndpointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Endpoints.
   */
  cursor?: Prisma.EndpointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Endpoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Endpoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Endpoints.
   */
  distinct?: Prisma.EndpointScalarFieldEnum | Prisma.EndpointScalarFieldEnum[]
}

/**
 * Endpoint findMany
 */
export type EndpointFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  /**
   * Filter, which Endpoints to fetch.
   */
  where?: Prisma.EndpointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Endpoints to fetch.
   */
  orderBy?: Prisma.EndpointOrderByWithRelationInput | Prisma.EndpointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Endpoints.
   */
  cursor?: Prisma.EndpointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Endpoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Endpoints.
   */
  skip?: number
  distinct?: Prisma.EndpointScalarFieldEnum | Prisma.EndpointScalarFieldEnum[]
}

/**
 * Endpoint create
 */
export type EndpointCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  /**
   * The data needed to create a Endpoint.
   */
  data: Prisma.XOR<Prisma.EndpointCreateInput, Prisma.EndpointUncheckedCreateInput>
}

/**
 * Endpoint createMany
 */
export type EndpointCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Endpoints.
   */
  data: Prisma.EndpointCreateManyInput | Prisma.EndpointCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Endpoint createManyAndReturn
 */
export type EndpointCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * The data used to create many Endpoints.
   */
  data: Prisma.EndpointCreateManyInput | Prisma.EndpointCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Endpoint update
 */
export type EndpointUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  /**
   * The data needed to update a Endpoint.
   */
  data: Prisma.XOR<Prisma.EndpointUpdateInput, Prisma.EndpointUncheckedUpdateInput>
  /**
   * Choose, which Endpoint to update.
   */
  where: Prisma.EndpointWhereUniqueInput
}

/**
 * Endpoint updateMany
 */
export type EndpointUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Endpoints.
   */
  data: Prisma.XOR<Prisma.EndpointUpdateManyMutationInput, Prisma.EndpointUncheckedUpdateManyInput>
  /**
   * Filter which Endpoints to update
   */
  where?: Prisma.EndpointWhereInput
  /**
   * Limit how many Endpoints to update.
   */
  limit?: number
}

/**
 * Endpoint updateManyAndReturn
 */
export type EndpointUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * The data used to update Endpoints.
   */
  data: Prisma.XOR<Prisma.EndpointUpdateManyMutationInput, Prisma.EndpointUncheckedUpdateManyInput>
  /**
   * Filter which Endpoints to update
   */
  where?: Prisma.EndpointWhereInput
  /**
   * Limit how many Endpoints to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Endpoint upsert
 */
export type EndpointUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  /**
   * The filter to search for the Endpoint to update in case it exists.
   */
  where: Prisma.EndpointWhereUniqueInput
  /**
   * In case the Endpoint found by the `where` argument doesn't exist, create a new Endpoint with this data.
   */
  create: Prisma.XOR<Prisma.EndpointCreateInput, Prisma.EndpointUncheckedCreateInput>
  /**
   * In case the Endpoint was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EndpointUpdateInput, Prisma.EndpointUncheckedUpdateInput>
}

/**
 * Endpoint delete
 */
export type EndpointDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  /**
   * Filter which Endpoint to delete.
   */
  where: Prisma.EndpointWhereUniqueInput
}

/**
 * Endpoint deleteMany
 */
export type EndpointDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Endpoints to delete
   */
  where?: Prisma.EndpointWhereInput
  /**
   * Limit how many Endpoints to delete.
   */
  limit?: number
}

/**
 * Endpoint without action
 */
export type EndpointDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
}
