
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EndpointVersion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EndpointVersion
 * 
 */
export type EndpointVersionModel = runtime.Types.Result.DefaultSelection<Prisma.$EndpointVersionPayload>

export type AggregateEndpointVersion = {
  _count: EndpointVersionCountAggregateOutputType | null
  _avg: EndpointVersionAvgAggregateOutputType | null
  _sum: EndpointVersionSumAggregateOutputType | null
  _min: EndpointVersionMinAggregateOutputType | null
  _max: EndpointVersionMaxAggregateOutputType | null
}

export type EndpointVersionAvgAggregateOutputType = {
  version: number | null
}

export type EndpointVersionSumAggregateOutputType = {
  version: number | null
}

export type EndpointVersionMinAggregateOutputType = {
  id: string | null
  type: $Enums.EndpointType | null
  version: number | null
}

export type EndpointVersionMaxAggregateOutputType = {
  id: string | null
  type: $Enums.EndpointType | null
  version: number | null
}

export type EndpointVersionCountAggregateOutputType = {
  id: number
  type: number
  version: number
  _all: number
}


export type EndpointVersionAvgAggregateInputType = {
  version?: true
}

export type EndpointVersionSumAggregateInputType = {
  version?: true
}

export type EndpointVersionMinAggregateInputType = {
  id?: true
  type?: true
  version?: true
}

export type EndpointVersionMaxAggregateInputType = {
  id?: true
  type?: true
  version?: true
}

export type EndpointVersionCountAggregateInputType = {
  id?: true
  type?: true
  version?: true
  _all?: true
}

export type EndpointVersionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EndpointVersion to aggregate.
   */
  where?: Prisma.EndpointVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EndpointVersions to fetch.
   */
  orderBy?: Prisma.EndpointVersionOrderByWithRelationInput | Prisma.EndpointVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EndpointVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EndpointVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EndpointVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EndpointVersions
  **/
  _count?: true | EndpointVersionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EndpointVersionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EndpointVersionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EndpointVersionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EndpointVersionMaxAggregateInputType
}

export type GetEndpointVersionAggregateType<T extends EndpointVersionAggregateArgs> = {
      [P in keyof T & keyof AggregateEndpointVersion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEndpointVersion[P]>
    : Prisma.GetScalarType<T[P], AggregateEndpointVersion[P]>
}




export type EndpointVersionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EndpointVersionWhereInput
  orderBy?: Prisma.EndpointVersionOrderByWithAggregationInput | Prisma.EndpointVersionOrderByWithAggregationInput[]
  by: Prisma.EndpointVersionScalarFieldEnum[] | Prisma.EndpointVersionScalarFieldEnum
  having?: Prisma.EndpointVersionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EndpointVersionCountAggregateInputType | true
  _avg?: EndpointVersionAvgAggregateInputType
  _sum?: EndpointVersionSumAggregateInputType
  _min?: EndpointVersionMinAggregateInputType
  _max?: EndpointVersionMaxAggregateInputType
}

export type EndpointVersionGroupByOutputType = {
  id: string
  type: $Enums.EndpointType
  version: number
  _count: EndpointVersionCountAggregateOutputType | null
  _avg: EndpointVersionAvgAggregateOutputType | null
  _sum: EndpointVersionSumAggregateOutputType | null
  _min: EndpointVersionMinAggregateOutputType | null
  _max: EndpointVersionMaxAggregateOutputType | null
}

type GetEndpointVersionGroupByPayload<T extends EndpointVersionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EndpointVersionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EndpointVersionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EndpointVersionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EndpointVersionGroupByOutputType[P]>
      }
    >
  >



export type EndpointVersionWhereInput = {
  AND?: Prisma.EndpointVersionWhereInput | Prisma.EndpointVersionWhereInput[]
  OR?: Prisma.EndpointVersionWhereInput[]
  NOT?: Prisma.EndpointVersionWhereInput | Prisma.EndpointVersionWhereInput[]
  id?: Prisma.StringFilter<"EndpointVersion"> | string
  type?: Prisma.EnumEndpointTypeFilter<"EndpointVersion"> | $Enums.EndpointType
  version?: Prisma.IntFilter<"EndpointVersion"> | number
  endpoint?: Prisma.EndpointListRelationFilter
}

export type EndpointVersionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  version?: Prisma.SortOrder
  endpoint?: Prisma.EndpointOrderByRelationAggregateInput
  _relevance?: Prisma.EndpointVersionOrderByRelevanceInput
}

export type EndpointVersionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  type_version?: Prisma.EndpointVersionTypeVersionCompoundUniqueInput
  AND?: Prisma.EndpointVersionWhereInput | Prisma.EndpointVersionWhereInput[]
  OR?: Prisma.EndpointVersionWhereInput[]
  NOT?: Prisma.EndpointVersionWhereInput | Prisma.EndpointVersionWhereInput[]
  type?: Prisma.EnumEndpointTypeFilter<"EndpointVersion"> | $Enums.EndpointType
  version?: Prisma.IntFilter<"EndpointVersion"> | number
  endpoint?: Prisma.EndpointListRelationFilter
}, "id" | "type_version">

export type EndpointVersionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  version?: Prisma.SortOrder
  _count?: Prisma.EndpointVersionCountOrderByAggregateInput
  _avg?: Prisma.EndpointVersionAvgOrderByAggregateInput
  _max?: Prisma.EndpointVersionMaxOrderByAggregateInput
  _min?: Prisma.EndpointVersionMinOrderByAggregateInput
  _sum?: Prisma.EndpointVersionSumOrderByAggregateInput
}

export type EndpointVersionScalarWhereWithAggregatesInput = {
  AND?: Prisma.EndpointVersionScalarWhereWithAggregatesInput | Prisma.EndpointVersionScalarWhereWithAggregatesInput[]
  OR?: Prisma.EndpointVersionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EndpointVersionScalarWhereWithAggregatesInput | Prisma.EndpointVersionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EndpointVersion"> | string
  type?: Prisma.EnumEndpointTypeWithAggregatesFilter<"EndpointVersion"> | $Enums.EndpointType
  version?: Prisma.IntWithAggregatesFilter<"EndpointVersion"> | number
}

export type EndpointVersionCreateInput = {
  id: string
  type: $Enums.EndpointType
  version?: number
  endpoint?: Prisma.EndpointCreateNestedManyWithoutVersionInput
}

export type EndpointVersionUncheckedCreateInput = {
  id: string
  type: $Enums.EndpointType
  version?: number
  endpoint?: Prisma.EndpointUncheckedCreateNestedManyWithoutVersionInput
}

export type EndpointVersionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  version?: Prisma.IntFieldUpdateOperationsInput | number
  endpoint?: Prisma.EndpointUpdateManyWithoutVersionNestedInput
}

export type EndpointVersionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  version?: Prisma.IntFieldUpdateOperationsInput | number
  endpoint?: Prisma.EndpointUncheckedUpdateManyWithoutVersionNestedInput
}

export type EndpointVersionCreateManyInput = {
  id: string
  type: $Enums.EndpointType
  version?: number
}

export type EndpointVersionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  version?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EndpointVersionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  version?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EndpointVersionOrderByRelevanceInput = {
  fields: Prisma.EndpointVersionOrderByRelevanceFieldEnum | Prisma.EndpointVersionOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type EndpointVersionTypeVersionCompoundUniqueInput = {
  type: $Enums.EndpointType
  version: number
}

export type EndpointVersionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  version?: Prisma.SortOrder
}

export type EndpointVersionAvgOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type EndpointVersionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  version?: Prisma.SortOrder
}

export type EndpointVersionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  version?: Prisma.SortOrder
}

export type EndpointVersionSumOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type EndpointVersionScalarRelationFilter = {
  is?: Prisma.EndpointVersionWhereInput
  isNot?: Prisma.EndpointVersionWhereInput
}

export type EnumEndpointTypeFieldUpdateOperationsInput = {
  set?: $Enums.EndpointType
}

export type EndpointVersionCreateNestedOneWithoutEndpointInput = {
  create?: Prisma.XOR<Prisma.EndpointVersionCreateWithoutEndpointInput, Prisma.EndpointVersionUncheckedCreateWithoutEndpointInput>
  connectOrCreate?: Prisma.EndpointVersionCreateOrConnectWithoutEndpointInput
  connect?: Prisma.EndpointVersionWhereUniqueInput
}

export type EndpointVersionUpdateOneRequiredWithoutEndpointNestedInput = {
  create?: Prisma.XOR<Prisma.EndpointVersionCreateWithoutEndpointInput, Prisma.EndpointVersionUncheckedCreateWithoutEndpointInput>
  connectOrCreate?: Prisma.EndpointVersionCreateOrConnectWithoutEndpointInput
  upsert?: Prisma.EndpointVersionUpsertWithoutEndpointInput
  connect?: Prisma.EndpointVersionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EndpointVersionUpdateToOneWithWhereWithoutEndpointInput, Prisma.EndpointVersionUpdateWithoutEndpointInput>, Prisma.EndpointVersionUncheckedUpdateWithoutEndpointInput>
}

export type EndpointVersionCreateWithoutEndpointInput = {
  id: string
  type: $Enums.EndpointType
  version?: number
}

export type EndpointVersionUncheckedCreateWithoutEndpointInput = {
  id: string
  type: $Enums.EndpointType
  version?: number
}

export type EndpointVersionCreateOrConnectWithoutEndpointInput = {
  where: Prisma.EndpointVersionWhereUniqueInput
  create: Prisma.XOR<Prisma.EndpointVersionCreateWithoutEndpointInput, Prisma.EndpointVersionUncheckedCreateWithoutEndpointInput>
}

export type EndpointVersionUpsertWithoutEndpointInput = {
  update: Prisma.XOR<Prisma.EndpointVersionUpdateWithoutEndpointInput, Prisma.EndpointVersionUncheckedUpdateWithoutEndpointInput>
  create: Prisma.XOR<Prisma.EndpointVersionCreateWithoutEndpointInput, Prisma.EndpointVersionUncheckedCreateWithoutEndpointInput>
  where?: Prisma.EndpointVersionWhereInput
}

export type EndpointVersionUpdateToOneWithWhereWithoutEndpointInput = {
  where?: Prisma.EndpointVersionWhereInput
  data: Prisma.XOR<Prisma.EndpointVersionUpdateWithoutEndpointInput, Prisma.EndpointVersionUncheckedUpdateWithoutEndpointInput>
}

export type EndpointVersionUpdateWithoutEndpointInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  version?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EndpointVersionUncheckedUpdateWithoutEndpointInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumEndpointTypeFieldUpdateOperationsInput | $Enums.EndpointType
  version?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type EndpointVersionCountOutputType
 */

export type EndpointVersionCountOutputType = {
  endpoint: number
}

export type EndpointVersionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  endpoint?: boolean | EndpointVersionCountOutputTypeCountEndpointArgs
}

/**
 * EndpointVersionCountOutputType without action
 */
export type EndpointVersionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersionCountOutputType
   */
  select?: Prisma.EndpointVersionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EndpointVersionCountOutputType without action
 */
export type EndpointVersionCountOutputTypeCountEndpointArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EndpointWhereInput
}


export type EndpointVersionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  version?: boolean
  endpoint?: boolean | Prisma.EndpointVersion$endpointArgs<ExtArgs>
  _count?: boolean | Prisma.EndpointVersionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["endpointVersion"]>

export type EndpointVersionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  version?: boolean
}, ExtArgs["result"]["endpointVersion"]>

export type EndpointVersionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  version?: boolean
}, ExtArgs["result"]["endpointVersion"]>

export type EndpointVersionSelectScalar = {
  id?: boolean
  type?: boolean
  version?: boolean
}

export type EndpointVersionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "version", ExtArgs["result"]["endpointVersion"]>
export type EndpointVersionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  endpoint?: boolean | Prisma.EndpointVersion$endpointArgs<ExtArgs>
  _count?: boolean | Prisma.EndpointVersionCountOutputTypeDefaultArgs<ExtArgs>
}
export type EndpointVersionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type EndpointVersionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $EndpointVersionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EndpointVersion"
  objects: {
    endpoint: Prisma.$EndpointPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: $Enums.EndpointType
    version: number
  }, ExtArgs["result"]["endpointVersion"]>
  composites: {}
}

export type EndpointVersionGetPayload<S extends boolean | null | undefined | EndpointVersionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload, S>

export type EndpointVersionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EndpointVersionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EndpointVersionCountAggregateInputType | true
  }

export interface EndpointVersionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EndpointVersion'], meta: { name: 'EndpointVersion' } }
  /**
   * Find zero or one EndpointVersion that matches the filter.
   * @param {EndpointVersionFindUniqueArgs} args - Arguments to find a EndpointVersion
   * @example
   * // Get one EndpointVersion
   * const endpointVersion = await prisma.endpointVersion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EndpointVersionFindUniqueArgs>(args: Prisma.SelectSubset<T, EndpointVersionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EndpointVersionClient<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EndpointVersion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EndpointVersionFindUniqueOrThrowArgs} args - Arguments to find a EndpointVersion
   * @example
   * // Get one EndpointVersion
   * const endpointVersion = await prisma.endpointVersion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EndpointVersionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EndpointVersionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EndpointVersionClient<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EndpointVersion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointVersionFindFirstArgs} args - Arguments to find a EndpointVersion
   * @example
   * // Get one EndpointVersion
   * const endpointVersion = await prisma.endpointVersion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EndpointVersionFindFirstArgs>(args?: Prisma.SelectSubset<T, EndpointVersionFindFirstArgs<ExtArgs>>): Prisma.Prisma__EndpointVersionClient<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EndpointVersion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointVersionFindFirstOrThrowArgs} args - Arguments to find a EndpointVersion
   * @example
   * // Get one EndpointVersion
   * const endpointVersion = await prisma.endpointVersion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EndpointVersionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EndpointVersionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EndpointVersionClient<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EndpointVersions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointVersionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EndpointVersions
   * const endpointVersions = await prisma.endpointVersion.findMany()
   * 
   * // Get first 10 EndpointVersions
   * const endpointVersions = await prisma.endpointVersion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const endpointVersionWithIdOnly = await prisma.endpointVersion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EndpointVersionFindManyArgs>(args?: Prisma.SelectSubset<T, EndpointVersionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EndpointVersion.
   * @param {EndpointVersionCreateArgs} args - Arguments to create a EndpointVersion.
   * @example
   * // Create one EndpointVersion
   * const EndpointVersion = await prisma.endpointVersion.create({
   *   data: {
   *     // ... data to create a EndpointVersion
   *   }
   * })
   * 
   */
  create<T extends EndpointVersionCreateArgs>(args: Prisma.SelectSubset<T, EndpointVersionCreateArgs<ExtArgs>>): Prisma.Prisma__EndpointVersionClient<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EndpointVersions.
   * @param {EndpointVersionCreateManyArgs} args - Arguments to create many EndpointVersions.
   * @example
   * // Create many EndpointVersions
   * const endpointVersion = await prisma.endpointVersion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EndpointVersionCreateManyArgs>(args?: Prisma.SelectSubset<T, EndpointVersionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EndpointVersions and returns the data saved in the database.
   * @param {EndpointVersionCreateManyAndReturnArgs} args - Arguments to create many EndpointVersions.
   * @example
   * // Create many EndpointVersions
   * const endpointVersion = await prisma.endpointVersion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EndpointVersions and only return the `id`
   * const endpointVersionWithIdOnly = await prisma.endpointVersion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EndpointVersionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EndpointVersionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EndpointVersion.
   * @param {EndpointVersionDeleteArgs} args - Arguments to delete one EndpointVersion.
   * @example
   * // Delete one EndpointVersion
   * const EndpointVersion = await prisma.endpointVersion.delete({
   *   where: {
   *     // ... filter to delete one EndpointVersion
   *   }
   * })
   * 
   */
  delete<T extends EndpointVersionDeleteArgs>(args: Prisma.SelectSubset<T, EndpointVersionDeleteArgs<ExtArgs>>): Prisma.Prisma__EndpointVersionClient<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EndpointVersion.
   * @param {EndpointVersionUpdateArgs} args - Arguments to update one EndpointVersion.
   * @example
   * // Update one EndpointVersion
   * const endpointVersion = await prisma.endpointVersion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EndpointVersionUpdateArgs>(args: Prisma.SelectSubset<T, EndpointVersionUpdateArgs<ExtArgs>>): Prisma.Prisma__EndpointVersionClient<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EndpointVersions.
   * @param {EndpointVersionDeleteManyArgs} args - Arguments to filter EndpointVersions to delete.
   * @example
   * // Delete a few EndpointVersions
   * const { count } = await prisma.endpointVersion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EndpointVersionDeleteManyArgs>(args?: Prisma.SelectSubset<T, EndpointVersionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EndpointVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointVersionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EndpointVersions
   * const endpointVersion = await prisma.endpointVersion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EndpointVersionUpdateManyArgs>(args: Prisma.SelectSubset<T, EndpointVersionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EndpointVersions and returns the data updated in the database.
   * @param {EndpointVersionUpdateManyAndReturnArgs} args - Arguments to update many EndpointVersions.
   * @example
   * // Update many EndpointVersions
   * const endpointVersion = await prisma.endpointVersion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EndpointVersions and only return the `id`
   * const endpointVersionWithIdOnly = await prisma.endpointVersion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EndpointVersionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EndpointVersionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EndpointVersion.
   * @param {EndpointVersionUpsertArgs} args - Arguments to update or create a EndpointVersion.
   * @example
   * // Update or create a EndpointVersion
   * const endpointVersion = await prisma.endpointVersion.upsert({
   *   create: {
   *     // ... data to create a EndpointVersion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EndpointVersion we want to update
   *   }
   * })
   */
  upsert<T extends EndpointVersionUpsertArgs>(args: Prisma.SelectSubset<T, EndpointVersionUpsertArgs<ExtArgs>>): Prisma.Prisma__EndpointVersionClient<runtime.Types.Result.GetResult<Prisma.$EndpointVersionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EndpointVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointVersionCountArgs} args - Arguments to filter EndpointVersions to count.
   * @example
   * // Count the number of EndpointVersions
   * const count = await prisma.endpointVersion.count({
   *   where: {
   *     // ... the filter for the EndpointVersions we want to count
   *   }
   * })
  **/
  count<T extends EndpointVersionCountArgs>(
    args?: Prisma.Subset<T, EndpointVersionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EndpointVersionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EndpointVersion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointVersionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EndpointVersionAggregateArgs>(args: Prisma.Subset<T, EndpointVersionAggregateArgs>): Prisma.PrismaPromise<GetEndpointVersionAggregateType<T>>

  /**
   * Group by EndpointVersion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndpointVersionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EndpointVersionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EndpointVersionGroupByArgs['orderBy'] }
      : { orderBy?: EndpointVersionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EndpointVersionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEndpointVersionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EndpointVersion model
 */
readonly fields: EndpointVersionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EndpointVersion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EndpointVersionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  endpoint<T extends Prisma.EndpointVersion$endpointArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EndpointVersion$endpointArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndpointPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EndpointVersion model
 */
export interface EndpointVersionFieldRefs {
  readonly id: Prisma.FieldRef<"EndpointVersion", 'String'>
  readonly type: Prisma.FieldRef<"EndpointVersion", 'EndpointType'>
  readonly version: Prisma.FieldRef<"EndpointVersion", 'Int'>
}
    

// Custom InputTypes
/**
 * EndpointVersion findUnique
 */
export type EndpointVersionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
  /**
   * Filter, which EndpointVersion to fetch.
   */
  where: Prisma.EndpointVersionWhereUniqueInput
}

/**
 * EndpointVersion findUniqueOrThrow
 */
export type EndpointVersionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
  /**
   * Filter, which EndpointVersion to fetch.
   */
  where: Prisma.EndpointVersionWhereUniqueInput
}

/**
 * EndpointVersion findFirst
 */
export type EndpointVersionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
  /**
   * Filter, which EndpointVersion to fetch.
   */
  where?: Prisma.EndpointVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EndpointVersions to fetch.
   */
  orderBy?: Prisma.EndpointVersionOrderByWithRelationInput | Prisma.EndpointVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EndpointVersions.
   */
  cursor?: Prisma.EndpointVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EndpointVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EndpointVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EndpointVersions.
   */
  distinct?: Prisma.EndpointVersionScalarFieldEnum | Prisma.EndpointVersionScalarFieldEnum[]
}

/**
 * EndpointVersion findFirstOrThrow
 */
export type EndpointVersionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
  /**
   * Filter, which EndpointVersion to fetch.
   */
  where?: Prisma.EndpointVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EndpointVersions to fetch.
   */
  orderBy?: Prisma.EndpointVersionOrderByWithRelationInput | Prisma.EndpointVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EndpointVersions.
   */
  cursor?: Prisma.EndpointVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EndpointVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EndpointVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EndpointVersions.
   */
  distinct?: Prisma.EndpointVersionScalarFieldEnum | Prisma.EndpointVersionScalarFieldEnum[]
}

/**
 * EndpointVersion findMany
 */
export type EndpointVersionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
  /**
   * Filter, which EndpointVersions to fetch.
   */
  where?: Prisma.EndpointVersionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EndpointVersions to fetch.
   */
  orderBy?: Prisma.EndpointVersionOrderByWithRelationInput | Prisma.EndpointVersionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EndpointVersions.
   */
  cursor?: Prisma.EndpointVersionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EndpointVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EndpointVersions.
   */
  skip?: number
  distinct?: Prisma.EndpointVersionScalarFieldEnum | Prisma.EndpointVersionScalarFieldEnum[]
}

/**
 * EndpointVersion create
 */
export type EndpointVersionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
  /**
   * The data needed to create a EndpointVersion.
   */
  data: Prisma.XOR<Prisma.EndpointVersionCreateInput, Prisma.EndpointVersionUncheckedCreateInput>
}

/**
 * EndpointVersion createMany
 */
export type EndpointVersionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EndpointVersions.
   */
  data: Prisma.EndpointVersionCreateManyInput | Prisma.EndpointVersionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EndpointVersion createManyAndReturn
 */
export type EndpointVersionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * The data used to create many EndpointVersions.
   */
  data: Prisma.EndpointVersionCreateManyInput | Prisma.EndpointVersionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EndpointVersion update
 */
export type EndpointVersionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
  /**
   * The data needed to update a EndpointVersion.
   */
  data: Prisma.XOR<Prisma.EndpointVersionUpdateInput, Prisma.EndpointVersionUncheckedUpdateInput>
  /**
   * Choose, which EndpointVersion to update.
   */
  where: Prisma.EndpointVersionWhereUniqueInput
}

/**
 * EndpointVersion updateMany
 */
export type EndpointVersionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EndpointVersions.
   */
  data: Prisma.XOR<Prisma.EndpointVersionUpdateManyMutationInput, Prisma.EndpointVersionUncheckedUpdateManyInput>
  /**
   * Filter which EndpointVersions to update
   */
  where?: Prisma.EndpointVersionWhereInput
  /**
   * Limit how many EndpointVersions to update.
   */
  limit?: number
}

/**
 * EndpointVersion updateManyAndReturn
 */
export type EndpointVersionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * The data used to update EndpointVersions.
   */
  data: Prisma.XOR<Prisma.EndpointVersionUpdateManyMutationInput, Prisma.EndpointVersionUncheckedUpdateManyInput>
  /**
   * Filter which EndpointVersions to update
   */
  where?: Prisma.EndpointVersionWhereInput
  /**
   * Limit how many EndpointVersions to update.
   */
  limit?: number
}

/**
 * EndpointVersion upsert
 */
export type EndpointVersionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
  /**
   * The filter to search for the EndpointVersion to update in case it exists.
   */
  where: Prisma.EndpointVersionWhereUniqueInput
  /**
   * In case the EndpointVersion found by the `where` argument doesn't exist, create a new EndpointVersion with this data.
   */
  create: Prisma.XOR<Prisma.EndpointVersionCreateInput, Prisma.EndpointVersionUncheckedCreateInput>
  /**
   * In case the EndpointVersion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EndpointVersionUpdateInput, Prisma.EndpointVersionUncheckedUpdateInput>
}

/**
 * EndpointVersion delete
 */
export type EndpointVersionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
  /**
   * Filter which EndpointVersion to delete.
   */
  where: Prisma.EndpointVersionWhereUniqueInput
}

/**
 * EndpointVersion deleteMany
 */
export type EndpointVersionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EndpointVersions to delete
   */
  where?: Prisma.EndpointVersionWhereInput
  /**
   * Limit how many EndpointVersions to delete.
   */
  limit?: number
}

/**
 * EndpointVersion.endpoint
 */
export type EndpointVersion$endpointArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Endpoint
   */
  select?: Prisma.EndpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Endpoint
   */
  omit?: Prisma.EndpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointInclude<ExtArgs> | null
  where?: Prisma.EndpointWhereInput
  orderBy?: Prisma.EndpointOrderByWithRelationInput | Prisma.EndpointOrderByWithRelationInput[]
  cursor?: Prisma.EndpointWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EndpointScalarFieldEnum | Prisma.EndpointScalarFieldEnum[]
}

/**
 * EndpointVersion without action
 */
export type EndpointVersionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndpointVersion
   */
  select?: Prisma.EndpointVersionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndpointVersion
   */
  omit?: Prisma.EndpointVersionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndpointVersionInclude<ExtArgs> | null
}
