
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserProject` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserProject
 * 
 */
export type UserProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$UserProjectPayload>

export type AggregateUserProject = {
  _count: UserProjectCountAggregateOutputType | null
  _min: UserProjectMinAggregateOutputType | null
  _max: UserProjectMaxAggregateOutputType | null
}

export type UserProjectMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  projectId: string | null
  userId: string | null
  roleId: string | null
}

export type UserProjectMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  projectId: string | null
  userId: string | null
  roleId: string | null
}

export type UserProjectCountAggregateOutputType = {
  id: number
  createdAt: number
  projectId: number
  userId: number
  roleId: number
  _all: number
}


export type UserProjectMinAggregateInputType = {
  id?: true
  createdAt?: true
  projectId?: true
  userId?: true
  roleId?: true
}

export type UserProjectMaxAggregateInputType = {
  id?: true
  createdAt?: true
  projectId?: true
  userId?: true
  roleId?: true
}

export type UserProjectCountAggregateInputType = {
  id?: true
  createdAt?: true
  projectId?: true
  userId?: true
  roleId?: true
  _all?: true
}

export type UserProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserProject to aggregate.
   */
  where?: Prisma.UserProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserProjects to fetch.
   */
  orderBy?: Prisma.UserProjectOrderByWithRelationInput | Prisma.UserProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserProjects
  **/
  _count?: true | UserProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserProjectMaxAggregateInputType
}

export type GetUserProjectAggregateType<T extends UserProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateUserProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserProject[P]>
    : Prisma.GetScalarType<T[P], AggregateUserProject[P]>
}




export type UserProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserProjectWhereInput
  orderBy?: Prisma.UserProjectOrderByWithAggregationInput | Prisma.UserProjectOrderByWithAggregationInput[]
  by: Prisma.UserProjectScalarFieldEnum[] | Prisma.UserProjectScalarFieldEnum
  having?: Prisma.UserProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserProjectCountAggregateInputType | true
  _min?: UserProjectMinAggregateInputType
  _max?: UserProjectMaxAggregateInputType
}

export type UserProjectGroupByOutputType = {
  id: string
  createdAt: Date
  projectId: string
  userId: string
  roleId: string
  _count: UserProjectCountAggregateOutputType | null
  _min: UserProjectMinAggregateOutputType | null
  _max: UserProjectMaxAggregateOutputType | null
}

type GetUserProjectGroupByPayload<T extends UserProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserProjectGroupByOutputType[P]>
      }
    >
  >



export type UserProjectWhereInput = {
  AND?: Prisma.UserProjectWhereInput | Prisma.UserProjectWhereInput[]
  OR?: Prisma.UserProjectWhereInput[]
  NOT?: Prisma.UserProjectWhereInput | Prisma.UserProjectWhereInput[]
  id?: Prisma.StringFilter<"UserProject"> | string
  createdAt?: Prisma.DateTimeFilter<"UserProject"> | Date | string
  projectId?: Prisma.StringFilter<"UserProject"> | string
  userId?: Prisma.StringFilter<"UserProject"> | string
  roleId?: Prisma.StringFilter<"UserProject"> | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
}

export type UserProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  role?: Prisma.RoleOrderByWithRelationInput
  _relevance?: Prisma.UserProjectOrderByRelevanceInput
}

export type UserProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  projectId_userId?: Prisma.UserProjectProjectIdUserIdCompoundUniqueInput
  AND?: Prisma.UserProjectWhereInput | Prisma.UserProjectWhereInput[]
  OR?: Prisma.UserProjectWhereInput[]
  NOT?: Prisma.UserProjectWhereInput | Prisma.UserProjectWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"UserProject"> | Date | string
  projectId?: Prisma.StringFilter<"UserProject"> | string
  userId?: Prisma.StringFilter<"UserProject"> | string
  roleId?: Prisma.StringFilter<"UserProject"> | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
}, "id" | "projectId_userId">

export type UserProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  _count?: Prisma.UserProjectCountOrderByAggregateInput
  _max?: Prisma.UserProjectMaxOrderByAggregateInput
  _min?: Prisma.UserProjectMinOrderByAggregateInput
}

export type UserProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserProjectScalarWhereWithAggregatesInput | Prisma.UserProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserProjectScalarWhereWithAggregatesInput | Prisma.UserProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserProject"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserProject"> | Date | string
  projectId?: Prisma.StringWithAggregatesFilter<"UserProject"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserProject"> | string
  roleId?: Prisma.StringWithAggregatesFilter<"UserProject"> | string
}

export type UserProjectCreateInput = {
  id: string
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutUserProjectsInput
  user: Prisma.UserCreateNestedOneWithoutUserProjectsInput
  role: Prisma.RoleCreateNestedOneWithoutUserProjectsInput
}

export type UserProjectUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  projectId: string
  userId: string
  roleId: string
}

export type UserProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutUserProjectsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutUserProjectsNestedInput
  role?: Prisma.RoleUpdateOneRequiredWithoutUserProjectsNestedInput
}

export type UserProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProjectCreateManyInput = {
  id: string
  createdAt?: Date | string
  projectId: string
  userId: string
  roleId: string
}

export type UserProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProjectListRelationFilter = {
  every?: Prisma.UserProjectWhereInput
  some?: Prisma.UserProjectWhereInput
  none?: Prisma.UserProjectWhereInput
}

export type UserProjectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserProjectOrderByRelevanceInput = {
  fields: Prisma.UserProjectOrderByRelevanceFieldEnum | Prisma.UserProjectOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type UserProjectProjectIdUserIdCompoundUniqueInput = {
  projectId: string
  userId: string
}

export type UserProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
}

export type UserProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
}

export type UserProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
}

export type UserProjectCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutUserInput, Prisma.UserProjectUncheckedCreateWithoutUserInput> | Prisma.UserProjectCreateWithoutUserInput[] | Prisma.UserProjectUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutUserInput | Prisma.UserProjectCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserProjectCreateManyUserInputEnvelope
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
}

export type UserProjectUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutUserInput, Prisma.UserProjectUncheckedCreateWithoutUserInput> | Prisma.UserProjectCreateWithoutUserInput[] | Prisma.UserProjectUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutUserInput | Prisma.UserProjectCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserProjectCreateManyUserInputEnvelope
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
}

export type UserProjectUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutUserInput, Prisma.UserProjectUncheckedCreateWithoutUserInput> | Prisma.UserProjectCreateWithoutUserInput[] | Prisma.UserProjectUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutUserInput | Prisma.UserProjectCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserProjectUpsertWithWhereUniqueWithoutUserInput | Prisma.UserProjectUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserProjectCreateManyUserInputEnvelope
  set?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  disconnect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  delete?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  update?: Prisma.UserProjectUpdateWithWhereUniqueWithoutUserInput | Prisma.UserProjectUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserProjectUpdateManyWithWhereWithoutUserInput | Prisma.UserProjectUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserProjectScalarWhereInput | Prisma.UserProjectScalarWhereInput[]
}

export type UserProjectUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutUserInput, Prisma.UserProjectUncheckedCreateWithoutUserInput> | Prisma.UserProjectCreateWithoutUserInput[] | Prisma.UserProjectUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutUserInput | Prisma.UserProjectCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserProjectUpsertWithWhereUniqueWithoutUserInput | Prisma.UserProjectUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserProjectCreateManyUserInputEnvelope
  set?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  disconnect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  delete?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  update?: Prisma.UserProjectUpdateWithWhereUniqueWithoutUserInput | Prisma.UserProjectUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserProjectUpdateManyWithWhereWithoutUserInput | Prisma.UserProjectUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserProjectScalarWhereInput | Prisma.UserProjectScalarWhereInput[]
}

export type UserProjectCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutRoleInput, Prisma.UserProjectUncheckedCreateWithoutRoleInput> | Prisma.UserProjectCreateWithoutRoleInput[] | Prisma.UserProjectUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutRoleInput | Prisma.UserProjectCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.UserProjectCreateManyRoleInputEnvelope
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
}

export type UserProjectUncheckedCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutRoleInput, Prisma.UserProjectUncheckedCreateWithoutRoleInput> | Prisma.UserProjectCreateWithoutRoleInput[] | Prisma.UserProjectUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutRoleInput | Prisma.UserProjectCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.UserProjectCreateManyRoleInputEnvelope
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
}

export type UserProjectUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutRoleInput, Prisma.UserProjectUncheckedCreateWithoutRoleInput> | Prisma.UserProjectCreateWithoutRoleInput[] | Prisma.UserProjectUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutRoleInput | Prisma.UserProjectCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.UserProjectUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserProjectUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.UserProjectCreateManyRoleInputEnvelope
  set?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  disconnect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  delete?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  update?: Prisma.UserProjectUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserProjectUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.UserProjectUpdateManyWithWhereWithoutRoleInput | Prisma.UserProjectUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.UserProjectScalarWhereInput | Prisma.UserProjectScalarWhereInput[]
}

export type UserProjectUncheckedUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutRoleInput, Prisma.UserProjectUncheckedCreateWithoutRoleInput> | Prisma.UserProjectCreateWithoutRoleInput[] | Prisma.UserProjectUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutRoleInput | Prisma.UserProjectCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.UserProjectUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserProjectUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.UserProjectCreateManyRoleInputEnvelope
  set?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  disconnect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  delete?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  update?: Prisma.UserProjectUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserProjectUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.UserProjectUpdateManyWithWhereWithoutRoleInput | Prisma.UserProjectUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.UserProjectScalarWhereInput | Prisma.UserProjectScalarWhereInput[]
}

export type UserProjectCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutProjectInput, Prisma.UserProjectUncheckedCreateWithoutProjectInput> | Prisma.UserProjectCreateWithoutProjectInput[] | Prisma.UserProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutProjectInput | Prisma.UserProjectCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.UserProjectCreateManyProjectInputEnvelope
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
}

export type UserProjectUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutProjectInput, Prisma.UserProjectUncheckedCreateWithoutProjectInput> | Prisma.UserProjectCreateWithoutProjectInput[] | Prisma.UserProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutProjectInput | Prisma.UserProjectCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.UserProjectCreateManyProjectInputEnvelope
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
}

export type UserProjectUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutProjectInput, Prisma.UserProjectUncheckedCreateWithoutProjectInput> | Prisma.UserProjectCreateWithoutProjectInput[] | Prisma.UserProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutProjectInput | Prisma.UserProjectCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.UserProjectUpsertWithWhereUniqueWithoutProjectInput | Prisma.UserProjectUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.UserProjectCreateManyProjectInputEnvelope
  set?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  disconnect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  delete?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  update?: Prisma.UserProjectUpdateWithWhereUniqueWithoutProjectInput | Prisma.UserProjectUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.UserProjectUpdateManyWithWhereWithoutProjectInput | Prisma.UserProjectUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.UserProjectScalarWhereInput | Prisma.UserProjectScalarWhereInput[]
}

export type UserProjectUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.UserProjectCreateWithoutProjectInput, Prisma.UserProjectUncheckedCreateWithoutProjectInput> | Prisma.UserProjectCreateWithoutProjectInput[] | Prisma.UserProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.UserProjectCreateOrConnectWithoutProjectInput | Prisma.UserProjectCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.UserProjectUpsertWithWhereUniqueWithoutProjectInput | Prisma.UserProjectUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.UserProjectCreateManyProjectInputEnvelope
  set?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  disconnect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  delete?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  connect?: Prisma.UserProjectWhereUniqueInput | Prisma.UserProjectWhereUniqueInput[]
  update?: Prisma.UserProjectUpdateWithWhereUniqueWithoutProjectInput | Prisma.UserProjectUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.UserProjectUpdateManyWithWhereWithoutProjectInput | Prisma.UserProjectUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.UserProjectScalarWhereInput | Prisma.UserProjectScalarWhereInput[]
}

export type UserProjectCreateWithoutUserInput = {
  id: string
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutUserProjectsInput
  role: Prisma.RoleCreateNestedOneWithoutUserProjectsInput
}

export type UserProjectUncheckedCreateWithoutUserInput = {
  id: string
  createdAt?: Date | string
  projectId: string
  roleId: string
}

export type UserProjectCreateOrConnectWithoutUserInput = {
  where: Prisma.UserProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.UserProjectCreateWithoutUserInput, Prisma.UserProjectUncheckedCreateWithoutUserInput>
}

export type UserProjectCreateManyUserInputEnvelope = {
  data: Prisma.UserProjectCreateManyUserInput | Prisma.UserProjectCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserProjectUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.UserProjectUpdateWithoutUserInput, Prisma.UserProjectUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserProjectCreateWithoutUserInput, Prisma.UserProjectUncheckedCreateWithoutUserInput>
}

export type UserProjectUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.UserProjectUpdateWithoutUserInput, Prisma.UserProjectUncheckedUpdateWithoutUserInput>
}

export type UserProjectUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserProjectScalarWhereInput
  data: Prisma.XOR<Prisma.UserProjectUpdateManyMutationInput, Prisma.UserProjectUncheckedUpdateManyWithoutUserInput>
}

export type UserProjectScalarWhereInput = {
  AND?: Prisma.UserProjectScalarWhereInput | Prisma.UserProjectScalarWhereInput[]
  OR?: Prisma.UserProjectScalarWhereInput[]
  NOT?: Prisma.UserProjectScalarWhereInput | Prisma.UserProjectScalarWhereInput[]
  id?: Prisma.StringFilter<"UserProject"> | string
  createdAt?: Prisma.DateTimeFilter<"UserProject"> | Date | string
  projectId?: Prisma.StringFilter<"UserProject"> | string
  userId?: Prisma.StringFilter<"UserProject"> | string
  roleId?: Prisma.StringFilter<"UserProject"> | string
}

export type UserProjectCreateWithoutRoleInput = {
  id: string
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutUserProjectsInput
  user: Prisma.UserCreateNestedOneWithoutUserProjectsInput
}

export type UserProjectUncheckedCreateWithoutRoleInput = {
  id: string
  createdAt?: Date | string
  projectId: string
  userId: string
}

export type UserProjectCreateOrConnectWithoutRoleInput = {
  where: Prisma.UserProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.UserProjectCreateWithoutRoleInput, Prisma.UserProjectUncheckedCreateWithoutRoleInput>
}

export type UserProjectCreateManyRoleInputEnvelope = {
  data: Prisma.UserProjectCreateManyRoleInput | Prisma.UserProjectCreateManyRoleInput[]
  skipDuplicates?: boolean
}

export type UserProjectUpsertWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.UserProjectUpdateWithoutRoleInput, Prisma.UserProjectUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.UserProjectCreateWithoutRoleInput, Prisma.UserProjectUncheckedCreateWithoutRoleInput>
}

export type UserProjectUpdateWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.UserProjectUpdateWithoutRoleInput, Prisma.UserProjectUncheckedUpdateWithoutRoleInput>
}

export type UserProjectUpdateManyWithWhereWithoutRoleInput = {
  where: Prisma.UserProjectScalarWhereInput
  data: Prisma.XOR<Prisma.UserProjectUpdateManyMutationInput, Prisma.UserProjectUncheckedUpdateManyWithoutRoleInput>
}

export type UserProjectCreateWithoutProjectInput = {
  id: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUserProjectsInput
  role: Prisma.RoleCreateNestedOneWithoutUserProjectsInput
}

export type UserProjectUncheckedCreateWithoutProjectInput = {
  id: string
  createdAt?: Date | string
  userId: string
  roleId: string
}

export type UserProjectCreateOrConnectWithoutProjectInput = {
  where: Prisma.UserProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.UserProjectCreateWithoutProjectInput, Prisma.UserProjectUncheckedCreateWithoutProjectInput>
}

export type UserProjectCreateManyProjectInputEnvelope = {
  data: Prisma.UserProjectCreateManyProjectInput | Prisma.UserProjectCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type UserProjectUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.UserProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.UserProjectUpdateWithoutProjectInput, Prisma.UserProjectUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.UserProjectCreateWithoutProjectInput, Prisma.UserProjectUncheckedCreateWithoutProjectInput>
}

export type UserProjectUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.UserProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.UserProjectUpdateWithoutProjectInput, Prisma.UserProjectUncheckedUpdateWithoutProjectInput>
}

export type UserProjectUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.UserProjectScalarWhereInput
  data: Prisma.XOR<Prisma.UserProjectUpdateManyMutationInput, Prisma.UserProjectUncheckedUpdateManyWithoutProjectInput>
}

export type UserProjectCreateManyUserInput = {
  id: string
  createdAt?: Date | string
  projectId: string
  roleId: string
}

export type UserProjectUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutUserProjectsNestedInput
  role?: Prisma.RoleUpdateOneRequiredWithoutUserProjectsNestedInput
}

export type UserProjectUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProjectUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProjectCreateManyRoleInput = {
  id: string
  createdAt?: Date | string
  projectId: string
  userId: string
}

export type UserProjectUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutUserProjectsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutUserProjectsNestedInput
}

export type UserProjectUncheckedUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProjectUncheckedUpdateManyWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProjectCreateManyProjectInput = {
  id: string
  createdAt?: Date | string
  userId: string
  roleId: string
}

export type UserProjectUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUserProjectsNestedInput
  role?: Prisma.RoleUpdateOneRequiredWithoutUserProjectsNestedInput
}

export type UserProjectUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserProjectUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type UserProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  projectId?: boolean
  userId?: boolean
  roleId?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userProject"]>

export type UserProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  projectId?: boolean
  userId?: boolean
  roleId?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userProject"]>

export type UserProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  projectId?: boolean
  userId?: boolean
  roleId?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userProject"]>

export type UserProjectSelectScalar = {
  id?: boolean
  createdAt?: boolean
  projectId?: boolean
  userId?: boolean
  roleId?: boolean
}

export type UserProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "projectId" | "userId" | "roleId", ExtArgs["result"]["userProject"]>
export type UserProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}
export type UserProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}
export type UserProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}

export type $UserProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserProject"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    role: Prisma.$RolePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    projectId: string
    userId: string
    roleId: string
  }, ExtArgs["result"]["userProject"]>
  composites: {}
}

export type UserProjectGetPayload<S extends boolean | null | undefined | UserProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserProjectPayload, S>

export type UserProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserProjectCountAggregateInputType | true
  }

export interface UserProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserProject'], meta: { name: 'UserProject' } }
  /**
   * Find zero or one UserProject that matches the filter.
   * @param {UserProjectFindUniqueArgs} args - Arguments to find a UserProject
   * @example
   * // Get one UserProject
   * const userProject = await prisma.userProject.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, UserProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserProjectClient<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserProject that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserProjectFindUniqueOrThrowArgs} args - Arguments to find a UserProject
   * @example
   * // Get one UserProject
   * const userProject = await prisma.userProject.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserProjectClient<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserProject that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProjectFindFirstArgs} args - Arguments to find a UserProject
   * @example
   * // Get one UserProject
   * const userProject = await prisma.userProject.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, UserProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserProjectClient<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserProject that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProjectFindFirstOrThrowArgs} args - Arguments to find a UserProject
   * @example
   * // Get one UserProject
   * const userProject = await prisma.userProject.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserProjectClient<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserProjects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserProjects
   * const userProjects = await prisma.userProject.findMany()
   * 
   * // Get first 10 UserProjects
   * const userProjects = await prisma.userProject.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userProjectWithIdOnly = await prisma.userProject.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserProjectFindManyArgs>(args?: Prisma.SelectSubset<T, UserProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserProject.
   * @param {UserProjectCreateArgs} args - Arguments to create a UserProject.
   * @example
   * // Create one UserProject
   * const UserProject = await prisma.userProject.create({
   *   data: {
   *     // ... data to create a UserProject
   *   }
   * })
   * 
   */
  create<T extends UserProjectCreateArgs>(args: Prisma.SelectSubset<T, UserProjectCreateArgs<ExtArgs>>): Prisma.Prisma__UserProjectClient<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserProjects.
   * @param {UserProjectCreateManyArgs} args - Arguments to create many UserProjects.
   * @example
   * // Create many UserProjects
   * const userProject = await prisma.userProject.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, UserProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserProjects and returns the data saved in the database.
   * @param {UserProjectCreateManyAndReturnArgs} args - Arguments to create many UserProjects.
   * @example
   * // Create many UserProjects
   * const userProject = await prisma.userProject.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserProjects and only return the `id`
   * const userProjectWithIdOnly = await prisma.userProject.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserProject.
   * @param {UserProjectDeleteArgs} args - Arguments to delete one UserProject.
   * @example
   * // Delete one UserProject
   * const UserProject = await prisma.userProject.delete({
   *   where: {
   *     // ... filter to delete one UserProject
   *   }
   * })
   * 
   */
  delete<T extends UserProjectDeleteArgs>(args: Prisma.SelectSubset<T, UserProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__UserProjectClient<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserProject.
   * @param {UserProjectUpdateArgs} args - Arguments to update one UserProject.
   * @example
   * // Update one UserProject
   * const userProject = await prisma.userProject.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserProjectUpdateArgs>(args: Prisma.SelectSubset<T, UserProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__UserProjectClient<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserProjects.
   * @param {UserProjectDeleteManyArgs} args - Arguments to filter UserProjects to delete.
   * @example
   * // Delete a few UserProjects
   * const { count } = await prisma.userProject.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserProjects
   * const userProject = await prisma.userProject.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, UserProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserProjects and returns the data updated in the database.
   * @param {UserProjectUpdateManyAndReturnArgs} args - Arguments to update many UserProjects.
   * @example
   * // Update many UserProjects
   * const userProject = await prisma.userProject.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserProjects and only return the `id`
   * const userProjectWithIdOnly = await prisma.userProject.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserProject.
   * @param {UserProjectUpsertArgs} args - Arguments to update or create a UserProject.
   * @example
   * // Update or create a UserProject
   * const userProject = await prisma.userProject.upsert({
   *   create: {
   *     // ... data to create a UserProject
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserProject we want to update
   *   }
   * })
   */
  upsert<T extends UserProjectUpsertArgs>(args: Prisma.SelectSubset<T, UserProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__UserProjectClient<runtime.Types.Result.GetResult<Prisma.$UserProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProjectCountArgs} args - Arguments to filter UserProjects to count.
   * @example
   * // Count the number of UserProjects
   * const count = await prisma.userProject.count({
   *   where: {
   *     // ... the filter for the UserProjects we want to count
   *   }
   * })
  **/
  count<T extends UserProjectCountArgs>(
    args?: Prisma.Subset<T, UserProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserProjectAggregateArgs>(args: Prisma.Subset<T, UserProjectAggregateArgs>): Prisma.PrismaPromise<GetUserProjectAggregateType<T>>

  /**
   * Group by UserProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserProjectGroupByArgs['orderBy'] }
      : { orderBy?: UserProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserProject model
 */
readonly fields: UserProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserProject.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  role<T extends Prisma.RoleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoleDefaultArgs<ExtArgs>>): Prisma.Prisma__RoleClient<runtime.Types.Result.GetResult<Prisma.$RolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserProject model
 */
export interface UserProjectFieldRefs {
  readonly id: Prisma.FieldRef<"UserProject", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserProject", 'DateTime'>
  readonly projectId: Prisma.FieldRef<"UserProject", 'String'>
  readonly userId: Prisma.FieldRef<"UserProject", 'String'>
  readonly roleId: Prisma.FieldRef<"UserProject", 'String'>
}
    

// Custom InputTypes
/**
 * UserProject findUnique
 */
export type UserProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
  /**
   * Filter, which UserProject to fetch.
   */
  where: Prisma.UserProjectWhereUniqueInput
}

/**
 * UserProject findUniqueOrThrow
 */
export type UserProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
  /**
   * Filter, which UserProject to fetch.
   */
  where: Prisma.UserProjectWhereUniqueInput
}

/**
 * UserProject findFirst
 */
export type UserProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
  /**
   * Filter, which UserProject to fetch.
   */
  where?: Prisma.UserProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserProjects to fetch.
   */
  orderBy?: Prisma.UserProjectOrderByWithRelationInput | Prisma.UserProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserProjects.
   */
  cursor?: Prisma.UserProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserProjects.
   */
  distinct?: Prisma.UserProjectScalarFieldEnum | Prisma.UserProjectScalarFieldEnum[]
}

/**
 * UserProject findFirstOrThrow
 */
export type UserProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
  /**
   * Filter, which UserProject to fetch.
   */
  where?: Prisma.UserProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserProjects to fetch.
   */
  orderBy?: Prisma.UserProjectOrderByWithRelationInput | Prisma.UserProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserProjects.
   */
  cursor?: Prisma.UserProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserProjects.
   */
  distinct?: Prisma.UserProjectScalarFieldEnum | Prisma.UserProjectScalarFieldEnum[]
}

/**
 * UserProject findMany
 */
export type UserProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
  /**
   * Filter, which UserProjects to fetch.
   */
  where?: Prisma.UserProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserProjects to fetch.
   */
  orderBy?: Prisma.UserProjectOrderByWithRelationInput | Prisma.UserProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserProjects.
   */
  cursor?: Prisma.UserProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserProjects.
   */
  skip?: number
  distinct?: Prisma.UserProjectScalarFieldEnum | Prisma.UserProjectScalarFieldEnum[]
}

/**
 * UserProject create
 */
export type UserProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a UserProject.
   */
  data: Prisma.XOR<Prisma.UserProjectCreateInput, Prisma.UserProjectUncheckedCreateInput>
}

/**
 * UserProject createMany
 */
export type UserProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserProjects.
   */
  data: Prisma.UserProjectCreateManyInput | Prisma.UserProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserProject createManyAndReturn
 */
export type UserProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * The data used to create many UserProjects.
   */
  data: Prisma.UserProjectCreateManyInput | Prisma.UserProjectCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserProject update
 */
export type UserProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a UserProject.
   */
  data: Prisma.XOR<Prisma.UserProjectUpdateInput, Prisma.UserProjectUncheckedUpdateInput>
  /**
   * Choose, which UserProject to update.
   */
  where: Prisma.UserProjectWhereUniqueInput
}

/**
 * UserProject updateMany
 */
export type UserProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserProjects.
   */
  data: Prisma.XOR<Prisma.UserProjectUpdateManyMutationInput, Prisma.UserProjectUncheckedUpdateManyInput>
  /**
   * Filter which UserProjects to update
   */
  where?: Prisma.UserProjectWhereInput
  /**
   * Limit how many UserProjects to update.
   */
  limit?: number
}

/**
 * UserProject updateManyAndReturn
 */
export type UserProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * The data used to update UserProjects.
   */
  data: Prisma.XOR<Prisma.UserProjectUpdateManyMutationInput, Prisma.UserProjectUncheckedUpdateManyInput>
  /**
   * Filter which UserProjects to update
   */
  where?: Prisma.UserProjectWhereInput
  /**
   * Limit how many UserProjects to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserProject upsert
 */
export type UserProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the UserProject to update in case it exists.
   */
  where: Prisma.UserProjectWhereUniqueInput
  /**
   * In case the UserProject found by the `where` argument doesn't exist, create a new UserProject with this data.
   */
  create: Prisma.XOR<Prisma.UserProjectCreateInput, Prisma.UserProjectUncheckedCreateInput>
  /**
   * In case the UserProject was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserProjectUpdateInput, Prisma.UserProjectUncheckedUpdateInput>
}

/**
 * UserProject delete
 */
export type UserProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
  /**
   * Filter which UserProject to delete.
   */
  where: Prisma.UserProjectWhereUniqueInput
}

/**
 * UserProject deleteMany
 */
export type UserProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserProjects to delete
   */
  where?: Prisma.UserProjectWhereInput
  /**
   * Limit how many UserProjects to delete.
   */
  limit?: number
}

/**
 * UserProject without action
 */
export type UserProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProject
   */
  select?: Prisma.UserProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProject
   */
  omit?: Prisma.UserProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProjectInclude<ExtArgs> | null
}
