
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserOrganization` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserOrganization
 * 
 */
export type UserOrganizationModel = runtime.Types.Result.DefaultSelection<Prisma.$UserOrganizationPayload>

export type AggregateUserOrganization = {
  _count: UserOrganizationCountAggregateOutputType | null
  _min: UserOrganizationMinAggregateOutputType | null
  _max: UserOrganizationMaxAggregateOutputType | null
}

export type UserOrganizationMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  organizationId: string | null
  userId: string | null
  roleId: string | null
}

export type UserOrganizationMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  organizationId: string | null
  userId: string | null
  roleId: string | null
}

export type UserOrganizationCountAggregateOutputType = {
  id: number
  createdAt: number
  organizationId: number
  userId: number
  roleId: number
  _all: number
}


export type UserOrganizationMinAggregateInputType = {
  id?: true
  createdAt?: true
  organizationId?: true
  userId?: true
  roleId?: true
}

export type UserOrganizationMaxAggregateInputType = {
  id?: true
  createdAt?: true
  organizationId?: true
  userId?: true
  roleId?: true
}

export type UserOrganizationCountAggregateInputType = {
  id?: true
  createdAt?: true
  organizationId?: true
  userId?: true
  roleId?: true
  _all?: true
}

export type UserOrganizationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserOrganization to aggregate.
   */
  where?: Prisma.UserOrganizationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserOrganizations to fetch.
   */
  orderBy?: Prisma.UserOrganizationOrderByWithRelationInput | Prisma.UserOrganizationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserOrganizationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserOrganizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserOrganizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserOrganizations
  **/
  _count?: true | UserOrganizationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserOrganizationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserOrganizationMaxAggregateInputType
}

export type GetUserOrganizationAggregateType<T extends UserOrganizationAggregateArgs> = {
      [P in keyof T & keyof AggregateUserOrganization]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserOrganization[P]>
    : Prisma.GetScalarType<T[P], AggregateUserOrganization[P]>
}




export type UserOrganizationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserOrganizationWhereInput
  orderBy?: Prisma.UserOrganizationOrderByWithAggregationInput | Prisma.UserOrganizationOrderByWithAggregationInput[]
  by: Prisma.UserOrganizationScalarFieldEnum[] | Prisma.UserOrganizationScalarFieldEnum
  having?: Prisma.UserOrganizationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserOrganizationCountAggregateInputType | true
  _min?: UserOrganizationMinAggregateInputType
  _max?: UserOrganizationMaxAggregateInputType
}

export type UserOrganizationGroupByOutputType = {
  id: string
  createdAt: Date
  organizationId: string
  userId: string
  roleId: string
  _count: UserOrganizationCountAggregateOutputType | null
  _min: UserOrganizationMinAggregateOutputType | null
  _max: UserOrganizationMaxAggregateOutputType | null
}

type GetUserOrganizationGroupByPayload<T extends UserOrganizationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserOrganizationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserOrganizationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserOrganizationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserOrganizationGroupByOutputType[P]>
      }
    >
  >



export type UserOrganizationWhereInput = {
  AND?: Prisma.UserOrganizationWhereInput | Prisma.UserOrganizationWhereInput[]
  OR?: Prisma.UserOrganizationWhereInput[]
  NOT?: Prisma.UserOrganizationWhereInput | Prisma.UserOrganizationWhereInput[]
  id?: Prisma.StringFilter<"UserOrganization"> | string
  createdAt?: Prisma.DateTimeFilter<"UserOrganization"> | Date | string
  organizationId?: Prisma.StringFilter<"UserOrganization"> | string
  userId?: Prisma.StringFilter<"UserOrganization"> | string
  roleId?: Prisma.StringFilter<"UserOrganization"> | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
}

export type UserOrganizationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  organization?: Prisma.OrganizationOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  role?: Prisma.RoleOrderByWithRelationInput
  _relevance?: Prisma.UserOrganizationOrderByRelevanceInput
}

export type UserOrganizationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  organizationId_userId?: Prisma.UserOrganizationOrganizationIdUserIdCompoundUniqueInput
  AND?: Prisma.UserOrganizationWhereInput | Prisma.UserOrganizationWhereInput[]
  OR?: Prisma.UserOrganizationWhereInput[]
  NOT?: Prisma.UserOrganizationWhereInput | Prisma.UserOrganizationWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"UserOrganization"> | Date | string
  organizationId?: Prisma.StringFilter<"UserOrganization"> | string
  userId?: Prisma.StringFilter<"UserOrganization"> | string
  roleId?: Prisma.StringFilter<"UserOrganization"> | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
}, "id" | "organizationId_userId">

export type UserOrganizationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  _count?: Prisma.UserOrganizationCountOrderByAggregateInput
  _max?: Prisma.UserOrganizationMaxOrderByAggregateInput
  _min?: Prisma.UserOrganizationMinOrderByAggregateInput
}

export type UserOrganizationScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserOrganizationScalarWhereWithAggregatesInput | Prisma.UserOrganizationScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserOrganizationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserOrganizationScalarWhereWithAggregatesInput | Prisma.UserOrganizationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserOrganization"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserOrganization"> | Date | string
  organizationId?: Prisma.StringWithAggregatesFilter<"UserOrganization"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserOrganization"> | string
  roleId?: Prisma.StringWithAggregatesFilter<"UserOrganization"> | string
}

export type UserOrganizationCreateInput = {
  id: string
  createdAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutUserOrganizationsInput
  user: Prisma.UserCreateNestedOneWithoutUserOrganizationsInput
  role: Prisma.RoleCreateNestedOneWithoutUserOrganizationsInput
}

export type UserOrganizationUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  organizationId: string
  userId: string
  roleId: string
}

export type UserOrganizationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutUserOrganizationsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutUserOrganizationsNestedInput
  role?: Prisma.RoleUpdateOneRequiredWithoutUserOrganizationsNestedInput
}

export type UserOrganizationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserOrganizationCreateManyInput = {
  id: string
  createdAt?: Date | string
  organizationId: string
  userId: string
  roleId: string
}

export type UserOrganizationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOrganizationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserOrganizationListRelationFilter = {
  every?: Prisma.UserOrganizationWhereInput
  some?: Prisma.UserOrganizationWhereInput
  none?: Prisma.UserOrganizationWhereInput
}

export type UserOrganizationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserOrganizationOrderByRelevanceInput = {
  fields: Prisma.UserOrganizationOrderByRelevanceFieldEnum | Prisma.UserOrganizationOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type UserOrganizationOrganizationIdUserIdCompoundUniqueInput = {
  organizationId: string
  userId: string
}

export type UserOrganizationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
}

export type UserOrganizationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
}

export type UserOrganizationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
}

export type UserOrganizationCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutUserInput, Prisma.UserOrganizationUncheckedCreateWithoutUserInput> | Prisma.UserOrganizationCreateWithoutUserInput[] | Prisma.UserOrganizationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutUserInput | Prisma.UserOrganizationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserOrganizationCreateManyUserInputEnvelope
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
}

export type UserOrganizationUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutUserInput, Prisma.UserOrganizationUncheckedCreateWithoutUserInput> | Prisma.UserOrganizationCreateWithoutUserInput[] | Prisma.UserOrganizationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutUserInput | Prisma.UserOrganizationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserOrganizationCreateManyUserInputEnvelope
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
}

export type UserOrganizationUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutUserInput, Prisma.UserOrganizationUncheckedCreateWithoutUserInput> | Prisma.UserOrganizationCreateWithoutUserInput[] | Prisma.UserOrganizationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutUserInput | Prisma.UserOrganizationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserOrganizationUpsertWithWhereUniqueWithoutUserInput | Prisma.UserOrganizationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserOrganizationCreateManyUserInputEnvelope
  set?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  disconnect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  delete?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  update?: Prisma.UserOrganizationUpdateWithWhereUniqueWithoutUserInput | Prisma.UserOrganizationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserOrganizationUpdateManyWithWhereWithoutUserInput | Prisma.UserOrganizationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserOrganizationScalarWhereInput | Prisma.UserOrganizationScalarWhereInput[]
}

export type UserOrganizationUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutUserInput, Prisma.UserOrganizationUncheckedCreateWithoutUserInput> | Prisma.UserOrganizationCreateWithoutUserInput[] | Prisma.UserOrganizationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutUserInput | Prisma.UserOrganizationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserOrganizationUpsertWithWhereUniqueWithoutUserInput | Prisma.UserOrganizationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserOrganizationCreateManyUserInputEnvelope
  set?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  disconnect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  delete?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  update?: Prisma.UserOrganizationUpdateWithWhereUniqueWithoutUserInput | Prisma.UserOrganizationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserOrganizationUpdateManyWithWhereWithoutUserInput | Prisma.UserOrganizationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserOrganizationScalarWhereInput | Prisma.UserOrganizationScalarWhereInput[]
}

export type UserOrganizationCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutRoleInput, Prisma.UserOrganizationUncheckedCreateWithoutRoleInput> | Prisma.UserOrganizationCreateWithoutRoleInput[] | Prisma.UserOrganizationUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutRoleInput | Prisma.UserOrganizationCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.UserOrganizationCreateManyRoleInputEnvelope
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
}

export type UserOrganizationUncheckedCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutRoleInput, Prisma.UserOrganizationUncheckedCreateWithoutRoleInput> | Prisma.UserOrganizationCreateWithoutRoleInput[] | Prisma.UserOrganizationUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutRoleInput | Prisma.UserOrganizationCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.UserOrganizationCreateManyRoleInputEnvelope
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
}

export type UserOrganizationUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutRoleInput, Prisma.UserOrganizationUncheckedCreateWithoutRoleInput> | Prisma.UserOrganizationCreateWithoutRoleInput[] | Prisma.UserOrganizationUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutRoleInput | Prisma.UserOrganizationCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.UserOrganizationUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserOrganizationUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.UserOrganizationCreateManyRoleInputEnvelope
  set?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  disconnect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  delete?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  update?: Prisma.UserOrganizationUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserOrganizationUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.UserOrganizationUpdateManyWithWhereWithoutRoleInput | Prisma.UserOrganizationUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.UserOrganizationScalarWhereInput | Prisma.UserOrganizationScalarWhereInput[]
}

export type UserOrganizationUncheckedUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutRoleInput, Prisma.UserOrganizationUncheckedCreateWithoutRoleInput> | Prisma.UserOrganizationCreateWithoutRoleInput[] | Prisma.UserOrganizationUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutRoleInput | Prisma.UserOrganizationCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.UserOrganizationUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserOrganizationUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.UserOrganizationCreateManyRoleInputEnvelope
  set?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  disconnect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  delete?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  update?: Prisma.UserOrganizationUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserOrganizationUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.UserOrganizationUpdateManyWithWhereWithoutRoleInput | Prisma.UserOrganizationUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.UserOrganizationScalarWhereInput | Prisma.UserOrganizationScalarWhereInput[]
}

export type UserOrganizationCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutOrganizationInput, Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput> | Prisma.UserOrganizationCreateWithoutOrganizationInput[] | Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutOrganizationInput | Prisma.UserOrganizationCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.UserOrganizationCreateManyOrganizationInputEnvelope
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
}

export type UserOrganizationUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutOrganizationInput, Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput> | Prisma.UserOrganizationCreateWithoutOrganizationInput[] | Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutOrganizationInput | Prisma.UserOrganizationCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.UserOrganizationCreateManyOrganizationInputEnvelope
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
}

export type UserOrganizationUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutOrganizationInput, Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput> | Prisma.UserOrganizationCreateWithoutOrganizationInput[] | Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutOrganizationInput | Prisma.UserOrganizationCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.UserOrganizationUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.UserOrganizationUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.UserOrganizationCreateManyOrganizationInputEnvelope
  set?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  disconnect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  delete?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  update?: Prisma.UserOrganizationUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.UserOrganizationUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.UserOrganizationUpdateManyWithWhereWithoutOrganizationInput | Prisma.UserOrganizationUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.UserOrganizationScalarWhereInput | Prisma.UserOrganizationScalarWhereInput[]
}

export type UserOrganizationUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.UserOrganizationCreateWithoutOrganizationInput, Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput> | Prisma.UserOrganizationCreateWithoutOrganizationInput[] | Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.UserOrganizationCreateOrConnectWithoutOrganizationInput | Prisma.UserOrganizationCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.UserOrganizationUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.UserOrganizationUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.UserOrganizationCreateManyOrganizationInputEnvelope
  set?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  disconnect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  delete?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  connect?: Prisma.UserOrganizationWhereUniqueInput | Prisma.UserOrganizationWhereUniqueInput[]
  update?: Prisma.UserOrganizationUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.UserOrganizationUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.UserOrganizationUpdateManyWithWhereWithoutOrganizationInput | Prisma.UserOrganizationUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.UserOrganizationScalarWhereInput | Prisma.UserOrganizationScalarWhereInput[]
}

export type UserOrganizationCreateWithoutUserInput = {
  id: string
  createdAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutUserOrganizationsInput
  role: Prisma.RoleCreateNestedOneWithoutUserOrganizationsInput
}

export type UserOrganizationUncheckedCreateWithoutUserInput = {
  id: string
  createdAt?: Date | string
  organizationId: string
  roleId: string
}

export type UserOrganizationCreateOrConnectWithoutUserInput = {
  where: Prisma.UserOrganizationWhereUniqueInput
  create: Prisma.XOR<Prisma.UserOrganizationCreateWithoutUserInput, Prisma.UserOrganizationUncheckedCreateWithoutUserInput>
}

export type UserOrganizationCreateManyUserInputEnvelope = {
  data: Prisma.UserOrganizationCreateManyUserInput | Prisma.UserOrganizationCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserOrganizationUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserOrganizationWhereUniqueInput
  update: Prisma.XOR<Prisma.UserOrganizationUpdateWithoutUserInput, Prisma.UserOrganizationUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserOrganizationCreateWithoutUserInput, Prisma.UserOrganizationUncheckedCreateWithoutUserInput>
}

export type UserOrganizationUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserOrganizationWhereUniqueInput
  data: Prisma.XOR<Prisma.UserOrganizationUpdateWithoutUserInput, Prisma.UserOrganizationUncheckedUpdateWithoutUserInput>
}

export type UserOrganizationUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserOrganizationScalarWhereInput
  data: Prisma.XOR<Prisma.UserOrganizationUpdateManyMutationInput, Prisma.UserOrganizationUncheckedUpdateManyWithoutUserInput>
}

export type UserOrganizationScalarWhereInput = {
  AND?: Prisma.UserOrganizationScalarWhereInput | Prisma.UserOrganizationScalarWhereInput[]
  OR?: Prisma.UserOrganizationScalarWhereInput[]
  NOT?: Prisma.UserOrganizationScalarWhereInput | Prisma.UserOrganizationScalarWhereInput[]
  id?: Prisma.StringFilter<"UserOrganization"> | string
  createdAt?: Prisma.DateTimeFilter<"UserOrganization"> | Date | string
  organizationId?: Prisma.StringFilter<"UserOrganization"> | string
  userId?: Prisma.StringFilter<"UserOrganization"> | string
  roleId?: Prisma.StringFilter<"UserOrganization"> | string
}

export type UserOrganizationCreateWithoutRoleInput = {
  id: string
  createdAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutUserOrganizationsInput
  user: Prisma.UserCreateNestedOneWithoutUserOrganizationsInput
}

export type UserOrganizationUncheckedCreateWithoutRoleInput = {
  id: string
  createdAt?: Date | string
  organizationId: string
  userId: string
}

export type UserOrganizationCreateOrConnectWithoutRoleInput = {
  where: Prisma.UserOrganizationWhereUniqueInput
  create: Prisma.XOR<Prisma.UserOrganizationCreateWithoutRoleInput, Prisma.UserOrganizationUncheckedCreateWithoutRoleInput>
}

export type UserOrganizationCreateManyRoleInputEnvelope = {
  data: Prisma.UserOrganizationCreateManyRoleInput | Prisma.UserOrganizationCreateManyRoleInput[]
  skipDuplicates?: boolean
}

export type UserOrganizationUpsertWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserOrganizationWhereUniqueInput
  update: Prisma.XOR<Prisma.UserOrganizationUpdateWithoutRoleInput, Prisma.UserOrganizationUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.UserOrganizationCreateWithoutRoleInput, Prisma.UserOrganizationUncheckedCreateWithoutRoleInput>
}

export type UserOrganizationUpdateWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserOrganizationWhereUniqueInput
  data: Prisma.XOR<Prisma.UserOrganizationUpdateWithoutRoleInput, Prisma.UserOrganizationUncheckedUpdateWithoutRoleInput>
}

export type UserOrganizationUpdateManyWithWhereWithoutRoleInput = {
  where: Prisma.UserOrganizationScalarWhereInput
  data: Prisma.XOR<Prisma.UserOrganizationUpdateManyMutationInput, Prisma.UserOrganizationUncheckedUpdateManyWithoutRoleInput>
}

export type UserOrganizationCreateWithoutOrganizationInput = {
  id: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUserOrganizationsInput
  role: Prisma.RoleCreateNestedOneWithoutUserOrganizationsInput
}

export type UserOrganizationUncheckedCreateWithoutOrganizationInput = {
  id: string
  createdAt?: Date | string
  userId: string
  roleId: string
}

export type UserOrganizationCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.UserOrganizationWhereUniqueInput
  create: Prisma.XOR<Prisma.UserOrganizationCreateWithoutOrganizationInput, Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput>
}

export type UserOrganizationCreateManyOrganizationInputEnvelope = {
  data: Prisma.UserOrganizationCreateManyOrganizationInput | Prisma.UserOrganizationCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type UserOrganizationUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.UserOrganizationWhereUniqueInput
  update: Prisma.XOR<Prisma.UserOrganizationUpdateWithoutOrganizationInput, Prisma.UserOrganizationUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.UserOrganizationCreateWithoutOrganizationInput, Prisma.UserOrganizationUncheckedCreateWithoutOrganizationInput>
}

export type UserOrganizationUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.UserOrganizationWhereUniqueInput
  data: Prisma.XOR<Prisma.UserOrganizationUpdateWithoutOrganizationInput, Prisma.UserOrganizationUncheckedUpdateWithoutOrganizationInput>
}

export type UserOrganizationUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.UserOrganizationScalarWhereInput
  data: Prisma.XOR<Prisma.UserOrganizationUpdateManyMutationInput, Prisma.UserOrganizationUncheckedUpdateManyWithoutOrganizationInput>
}

export type UserOrganizationCreateManyUserInput = {
  id: string
  createdAt?: Date | string
  organizationId: string
  roleId: string
}

export type UserOrganizationUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutUserOrganizationsNestedInput
  role?: Prisma.RoleUpdateOneRequiredWithoutUserOrganizationsNestedInput
}

export type UserOrganizationUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserOrganizationUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserOrganizationCreateManyRoleInput = {
  id: string
  createdAt?: Date | string
  organizationId: string
  userId: string
}

export type UserOrganizationUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutUserOrganizationsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutUserOrganizationsNestedInput
}

export type UserOrganizationUncheckedUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserOrganizationUncheckedUpdateManyWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserOrganizationCreateManyOrganizationInput = {
  id: string
  createdAt?: Date | string
  userId: string
  roleId: string
}

export type UserOrganizationUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUserOrganizationsNestedInput
  role?: Prisma.RoleUpdateOneRequiredWithoutUserOrganizationsNestedInput
}

export type UserOrganizationUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserOrganizationUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type UserOrganizationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  organizationId?: boolean
  userId?: boolean
  roleId?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userOrganization"]>

export type UserOrganizationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  organizationId?: boolean
  userId?: boolean
  roleId?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userOrganization"]>

export type UserOrganizationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  organizationId?: boolean
  userId?: boolean
  roleId?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userOrganization"]>

export type UserOrganizationSelectScalar = {
  id?: boolean
  createdAt?: boolean
  organizationId?: boolean
  userId?: boolean
  roleId?: boolean
}

export type UserOrganizationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "organizationId" | "userId" | "roleId", ExtArgs["result"]["userOrganization"]>
export type UserOrganizationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}
export type UserOrganizationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}
export type UserOrganizationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
}

export type $UserOrganizationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserOrganization"
  objects: {
    organization: Prisma.$OrganizationPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    role: Prisma.$RolePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    organizationId: string
    userId: string
    roleId: string
  }, ExtArgs["result"]["userOrganization"]>
  composites: {}
}

export type UserOrganizationGetPayload<S extends boolean | null | undefined | UserOrganizationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload, S>

export type UserOrganizationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserOrganizationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserOrganizationCountAggregateInputType | true
  }

export interface UserOrganizationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserOrganization'], meta: { name: 'UserOrganization' } }
  /**
   * Find zero or one UserOrganization that matches the filter.
   * @param {UserOrganizationFindUniqueArgs} args - Arguments to find a UserOrganization
   * @example
   * // Get one UserOrganization
   * const userOrganization = await prisma.userOrganization.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserOrganizationFindUniqueArgs>(args: Prisma.SelectSubset<T, UserOrganizationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserOrganizationClient<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserOrganization that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserOrganizationFindUniqueOrThrowArgs} args - Arguments to find a UserOrganization
   * @example
   * // Get one UserOrganization
   * const userOrganization = await prisma.userOrganization.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserOrganizationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserOrganizationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserOrganizationClient<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserOrganization that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOrganizationFindFirstArgs} args - Arguments to find a UserOrganization
   * @example
   * // Get one UserOrganization
   * const userOrganization = await prisma.userOrganization.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserOrganizationFindFirstArgs>(args?: Prisma.SelectSubset<T, UserOrganizationFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserOrganizationClient<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserOrganization that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOrganizationFindFirstOrThrowArgs} args - Arguments to find a UserOrganization
   * @example
   * // Get one UserOrganization
   * const userOrganization = await prisma.userOrganization.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserOrganizationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserOrganizationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserOrganizationClient<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserOrganizations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOrganizationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserOrganizations
   * const userOrganizations = await prisma.userOrganization.findMany()
   * 
   * // Get first 10 UserOrganizations
   * const userOrganizations = await prisma.userOrganization.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userOrganizationWithIdOnly = await prisma.userOrganization.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserOrganizationFindManyArgs>(args?: Prisma.SelectSubset<T, UserOrganizationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserOrganization.
   * @param {UserOrganizationCreateArgs} args - Arguments to create a UserOrganization.
   * @example
   * // Create one UserOrganization
   * const UserOrganization = await prisma.userOrganization.create({
   *   data: {
   *     // ... data to create a UserOrganization
   *   }
   * })
   * 
   */
  create<T extends UserOrganizationCreateArgs>(args: Prisma.SelectSubset<T, UserOrganizationCreateArgs<ExtArgs>>): Prisma.Prisma__UserOrganizationClient<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserOrganizations.
   * @param {UserOrganizationCreateManyArgs} args - Arguments to create many UserOrganizations.
   * @example
   * // Create many UserOrganizations
   * const userOrganization = await prisma.userOrganization.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserOrganizationCreateManyArgs>(args?: Prisma.SelectSubset<T, UserOrganizationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserOrganizations and returns the data saved in the database.
   * @param {UserOrganizationCreateManyAndReturnArgs} args - Arguments to create many UserOrganizations.
   * @example
   * // Create many UserOrganizations
   * const userOrganization = await prisma.userOrganization.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserOrganizations and only return the `id`
   * const userOrganizationWithIdOnly = await prisma.userOrganization.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserOrganizationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserOrganizationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserOrganization.
   * @param {UserOrganizationDeleteArgs} args - Arguments to delete one UserOrganization.
   * @example
   * // Delete one UserOrganization
   * const UserOrganization = await prisma.userOrganization.delete({
   *   where: {
   *     // ... filter to delete one UserOrganization
   *   }
   * })
   * 
   */
  delete<T extends UserOrganizationDeleteArgs>(args: Prisma.SelectSubset<T, UserOrganizationDeleteArgs<ExtArgs>>): Prisma.Prisma__UserOrganizationClient<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserOrganization.
   * @param {UserOrganizationUpdateArgs} args - Arguments to update one UserOrganization.
   * @example
   * // Update one UserOrganization
   * const userOrganization = await prisma.userOrganization.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserOrganizationUpdateArgs>(args: Prisma.SelectSubset<T, UserOrganizationUpdateArgs<ExtArgs>>): Prisma.Prisma__UserOrganizationClient<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserOrganizations.
   * @param {UserOrganizationDeleteManyArgs} args - Arguments to filter UserOrganizations to delete.
   * @example
   * // Delete a few UserOrganizations
   * const { count } = await prisma.userOrganization.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserOrganizationDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserOrganizationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserOrganizations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOrganizationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserOrganizations
   * const userOrganization = await prisma.userOrganization.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserOrganizationUpdateManyArgs>(args: Prisma.SelectSubset<T, UserOrganizationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserOrganizations and returns the data updated in the database.
   * @param {UserOrganizationUpdateManyAndReturnArgs} args - Arguments to update many UserOrganizations.
   * @example
   * // Update many UserOrganizations
   * const userOrganization = await prisma.userOrganization.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserOrganizations and only return the `id`
   * const userOrganizationWithIdOnly = await prisma.userOrganization.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserOrganizationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserOrganizationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserOrganization.
   * @param {UserOrganizationUpsertArgs} args - Arguments to update or create a UserOrganization.
   * @example
   * // Update or create a UserOrganization
   * const userOrganization = await prisma.userOrganization.upsert({
   *   create: {
   *     // ... data to create a UserOrganization
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserOrganization we want to update
   *   }
   * })
   */
  upsert<T extends UserOrganizationUpsertArgs>(args: Prisma.SelectSubset<T, UserOrganizationUpsertArgs<ExtArgs>>): Prisma.Prisma__UserOrganizationClient<runtime.Types.Result.GetResult<Prisma.$UserOrganizationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserOrganizations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOrganizationCountArgs} args - Arguments to filter UserOrganizations to count.
   * @example
   * // Count the number of UserOrganizations
   * const count = await prisma.userOrganization.count({
   *   where: {
   *     // ... the filter for the UserOrganizations we want to count
   *   }
   * })
  **/
  count<T extends UserOrganizationCountArgs>(
    args?: Prisma.Subset<T, UserOrganizationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserOrganizationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserOrganization.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOrganizationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserOrganizationAggregateArgs>(args: Prisma.Subset<T, UserOrganizationAggregateArgs>): Prisma.PrismaPromise<GetUserOrganizationAggregateType<T>>

  /**
   * Group by UserOrganization.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOrganizationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserOrganizationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserOrganizationGroupByArgs['orderBy'] }
      : { orderBy?: UserOrganizationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserOrganizationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserOrganizationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserOrganization model
 */
readonly fields: UserOrganizationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserOrganization.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserOrganizationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  role<T extends Prisma.RoleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoleDefaultArgs<ExtArgs>>): Prisma.Prisma__RoleClient<runtime.Types.Result.GetResult<Prisma.$RolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserOrganization model
 */
export interface UserOrganizationFieldRefs {
  readonly id: Prisma.FieldRef<"UserOrganization", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserOrganization", 'DateTime'>
  readonly organizationId: Prisma.FieldRef<"UserOrganization", 'String'>
  readonly userId: Prisma.FieldRef<"UserOrganization", 'String'>
  readonly roleId: Prisma.FieldRef<"UserOrganization", 'String'>
}
    

// Custom InputTypes
/**
 * UserOrganization findUnique
 */
export type UserOrganizationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
  /**
   * Filter, which UserOrganization to fetch.
   */
  where: Prisma.UserOrganizationWhereUniqueInput
}

/**
 * UserOrganization findUniqueOrThrow
 */
export type UserOrganizationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
  /**
   * Filter, which UserOrganization to fetch.
   */
  where: Prisma.UserOrganizationWhereUniqueInput
}

/**
 * UserOrganization findFirst
 */
export type UserOrganizationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
  /**
   * Filter, which UserOrganization to fetch.
   */
  where?: Prisma.UserOrganizationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserOrganizations to fetch.
   */
  orderBy?: Prisma.UserOrganizationOrderByWithRelationInput | Prisma.UserOrganizationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserOrganizations.
   */
  cursor?: Prisma.UserOrganizationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserOrganizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserOrganizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserOrganizations.
   */
  distinct?: Prisma.UserOrganizationScalarFieldEnum | Prisma.UserOrganizationScalarFieldEnum[]
}

/**
 * UserOrganization findFirstOrThrow
 */
export type UserOrganizationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
  /**
   * Filter, which UserOrganization to fetch.
   */
  where?: Prisma.UserOrganizationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserOrganizations to fetch.
   */
  orderBy?: Prisma.UserOrganizationOrderByWithRelationInput | Prisma.UserOrganizationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserOrganizations.
   */
  cursor?: Prisma.UserOrganizationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserOrganizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserOrganizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserOrganizations.
   */
  distinct?: Prisma.UserOrganizationScalarFieldEnum | Prisma.UserOrganizationScalarFieldEnum[]
}

/**
 * UserOrganization findMany
 */
export type UserOrganizationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
  /**
   * Filter, which UserOrganizations to fetch.
   */
  where?: Prisma.UserOrganizationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserOrganizations to fetch.
   */
  orderBy?: Prisma.UserOrganizationOrderByWithRelationInput | Prisma.UserOrganizationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserOrganizations.
   */
  cursor?: Prisma.UserOrganizationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserOrganizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserOrganizations.
   */
  skip?: number
  distinct?: Prisma.UserOrganizationScalarFieldEnum | Prisma.UserOrganizationScalarFieldEnum[]
}

/**
 * UserOrganization create
 */
export type UserOrganizationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
  /**
   * The data needed to create a UserOrganization.
   */
  data: Prisma.XOR<Prisma.UserOrganizationCreateInput, Prisma.UserOrganizationUncheckedCreateInput>
}

/**
 * UserOrganization createMany
 */
export type UserOrganizationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserOrganizations.
   */
  data: Prisma.UserOrganizationCreateManyInput | Prisma.UserOrganizationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserOrganization createManyAndReturn
 */
export type UserOrganizationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * The data used to create many UserOrganizations.
   */
  data: Prisma.UserOrganizationCreateManyInput | Prisma.UserOrganizationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserOrganization update
 */
export type UserOrganizationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
  /**
   * The data needed to update a UserOrganization.
   */
  data: Prisma.XOR<Prisma.UserOrganizationUpdateInput, Prisma.UserOrganizationUncheckedUpdateInput>
  /**
   * Choose, which UserOrganization to update.
   */
  where: Prisma.UserOrganizationWhereUniqueInput
}

/**
 * UserOrganization updateMany
 */
export type UserOrganizationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserOrganizations.
   */
  data: Prisma.XOR<Prisma.UserOrganizationUpdateManyMutationInput, Prisma.UserOrganizationUncheckedUpdateManyInput>
  /**
   * Filter which UserOrganizations to update
   */
  where?: Prisma.UserOrganizationWhereInput
  /**
   * Limit how many UserOrganizations to update.
   */
  limit?: number
}

/**
 * UserOrganization updateManyAndReturn
 */
export type UserOrganizationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * The data used to update UserOrganizations.
   */
  data: Prisma.XOR<Prisma.UserOrganizationUpdateManyMutationInput, Prisma.UserOrganizationUncheckedUpdateManyInput>
  /**
   * Filter which UserOrganizations to update
   */
  where?: Prisma.UserOrganizationWhereInput
  /**
   * Limit how many UserOrganizations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserOrganization upsert
 */
export type UserOrganizationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
  /**
   * The filter to search for the UserOrganization to update in case it exists.
   */
  where: Prisma.UserOrganizationWhereUniqueInput
  /**
   * In case the UserOrganization found by the `where` argument doesn't exist, create a new UserOrganization with this data.
   */
  create: Prisma.XOR<Prisma.UserOrganizationCreateInput, Prisma.UserOrganizationUncheckedCreateInput>
  /**
   * In case the UserOrganization was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserOrganizationUpdateInput, Prisma.UserOrganizationUncheckedUpdateInput>
}

/**
 * UserOrganization delete
 */
export type UserOrganizationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
  /**
   * Filter which UserOrganization to delete.
   */
  where: Prisma.UserOrganizationWhereUniqueInput
}

/**
 * UserOrganization deleteMany
 */
export type UserOrganizationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserOrganizations to delete
   */
  where?: Prisma.UserOrganizationWhereInput
  /**
   * Limit how many UserOrganizations to delete.
   */
  limit?: number
}

/**
 * UserOrganization without action
 */
export type UserOrganizationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOrganization
   */
  select?: Prisma.UserOrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOrganization
   */
  omit?: Prisma.UserOrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOrganizationInclude<ExtArgs> | null
}
